// <copyright file="IHttpClientConfiguration.cs" company="APIMatic">
// SplititWebApiV3.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using System;
using System.Collections.Generic;
using System.Net.Http;
using APIMatic.Core.Http.Configuration;

namespace SplititWebApiV3.Standard.Http.Client
{
    /// <summary>
    /// Represents the current state of the Http Client.
    /// </summary>
    public interface IHttpClientConfiguration : ICoreHttpClientConfiguration { }
}
