// <copyright file="AddressData.cs" company="APIMatic">
// SplititWebApiV3.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SplititWebApiV3.Standard;
using SplititWebApiV3.Standard.Utilities;

namespace SplititWebApiV3.Standard.Models
{
    /// <summary>
    /// AddressData.
    /// </summary>
    public class AddressData
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AddressData"/> class.
        /// </summary>
        public AddressData()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AddressData"/> class.
        /// </summary>
        /// <param name="addressLine">AddressLine.</param>
        /// <param name="addressLine2">AddressLine2.</param>
        /// <param name="city">City.</param>
        /// <param name="country">Country.</param>
        /// <param name="state">State.</param>
        /// <param name="zip">Zip.</param>
        public AddressData(
            string addressLine = "",
            string addressLine2 = "",
            string city = "",
            string country = "",
            string state = "",
            string zip = "")
        {
            this.AddressLine = addressLine;
            this.AddressLine2 = addressLine2;
            this.City = city;
            this.Country = country;
            this.State = state;
            this.Zip = zip;
        }

        /// <summary>
        /// Gets or sets AddressLine.
        /// </summary>
        [JsonProperty("AddressLine", NullValueHandling = NullValueHandling.Ignore)]
        public string AddressLine { get; set; }

        /// <summary>
        /// Gets or sets AddressLine2.
        /// </summary>
        [JsonProperty("AddressLine2", NullValueHandling = NullValueHandling.Ignore)]
        public string AddressLine2 { get; set; }

        /// <summary>
        /// Gets or sets City.
        /// </summary>
        [JsonProperty("City", NullValueHandling = NullValueHandling.Ignore)]
        public string City { get; set; }

        /// <summary>
        /// Gets or sets Country.
        /// </summary>
        [JsonProperty("Country", NullValueHandling = NullValueHandling.Ignore)]
        public string Country { get; set; }

        /// <summary>
        /// Gets or sets State.
        /// </summary>
        [JsonProperty("State", NullValueHandling = NullValueHandling.Ignore)]
        public string State { get; set; }

        /// <summary>
        /// Gets or sets Zip.
        /// </summary>
        [JsonProperty("Zip", NullValueHandling = NullValueHandling.Ignore)]
        public string Zip { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"AddressData : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is AddressData other &&
                (this.AddressLine == null && other.AddressLine == null ||
                 this.AddressLine?.Equals(other.AddressLine) == true) &&
                (this.AddressLine2 == null && other.AddressLine2 == null ||
                 this.AddressLine2?.Equals(other.AddressLine2) == true) &&
                (this.City == null && other.City == null ||
                 this.City?.Equals(other.City) == true) &&
                (this.Country == null && other.Country == null ||
                 this.Country?.Equals(other.Country) == true) &&
                (this.State == null && other.State == null ||
                 this.State?.Equals(other.State) == true) &&
                (this.Zip == null && other.Zip == null ||
                 this.Zip?.Equals(other.Zip) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"AddressLine = {this.AddressLine ?? "null"}");
            toStringOutput.Add($"AddressLine2 = {this.AddressLine2 ?? "null"}");
            toStringOutput.Add($"City = {this.City ?? "null"}");
            toStringOutput.Add($"Country = {this.Country ?? "null"}");
            toStringOutput.Add($"State = {this.State ?? "null"}");
            toStringOutput.Add($"Zip = {this.Zip ?? "null"}");
        }
    }
}