// <copyright file="AuthorizationModel.cs" company="APIMatic">
// SplititWebApiV3.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SplititWebApiV3.Standard;
using SplititWebApiV3.Standard.Utilities;

namespace SplititWebApiV3.Standard.Models
{
    /// <summary>
    /// AuthorizationModel.
    /// </summary>
    public class AuthorizationModel
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AuthorizationModel"/> class.
        /// </summary>
        public AuthorizationModel()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AuthorizationModel"/> class.
        /// </summary>
        /// <param name="status">Status.</param>
        /// <param name="date">Date.</param>
        /// <param name="splititErrorResultCode">SplititErrorResultCode.</param>
        /// <param name="gatewayTransactionID">GatewayTransactionID.</param>
        /// <param name="gatewayResultCode">GatewayResultCode.</param>
        /// <param name="gatewayResultMessage">GatewayResultMessage.</param>
        /// <param name="threeDSRedirect">ThreeDSRedirect.</param>
        /// <param name="cAVV">CAVV.</param>
        /// <param name="eCI">ECI.</param>
        /// <param name="gatewaySourceResponse">GatewaySourceResponse.</param>
        public AuthorizationModel(
            Models.GwAuthorizationStatusEnum status,
            DateTime? date = null,
            string splititErrorResultCode = "",
            string gatewayTransactionID = "",
            string gatewayResultCode = "",
            string gatewayResultMessage = "",
            Models.ThreeDsRedirectDataV3 threeDSRedirect = null,
            string cAVV = "",
            string eCI = "",
            string gatewaySourceResponse = "")
        {
            this.Status = status;
            this.Date = date;
            this.SplititErrorResultCode = splititErrorResultCode;
            this.GatewayTransactionID = gatewayTransactionID;
            this.GatewayResultCode = gatewayResultCode;
            this.GatewayResultMessage = gatewayResultMessage;
            this.ThreeDSRedirect = threeDSRedirect;
            this.CAVV = cAVV;
            this.ECI = eCI;
            this.GatewaySourceResponse = gatewaySourceResponse;
        }

        /// <summary>
        /// Gets or sets Status.
        /// </summary>
        [JsonProperty("Status")]
        public Models.GwAuthorizationStatusEnum Status { get; set; }

        /// <summary>
        /// Gets or sets Date.
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("Date", NullValueHandling = NullValueHandling.Ignore)]
        public DateTime? Date { get; set; }

        /// <summary>
        /// Gets or sets SplititErrorResultCode.
        /// </summary>
        [JsonProperty("SplititErrorResultCode", NullValueHandling = NullValueHandling.Ignore)]
        public string SplititErrorResultCode { get; set; }

        /// <summary>
        /// Gets or sets GatewayTransactionID.
        /// </summary>
        [JsonProperty("GatewayTransactionID", NullValueHandling = NullValueHandling.Ignore)]
        public string GatewayTransactionID { get; set; }

        /// <summary>
        /// Gets or sets GatewayResultCode.
        /// </summary>
        [JsonProperty("GatewayResultCode", NullValueHandling = NullValueHandling.Ignore)]
        public string GatewayResultCode { get; set; }

        /// <summary>
        /// Gets or sets GatewayResultMessage.
        /// </summary>
        [JsonProperty("GatewayResultMessage", NullValueHandling = NullValueHandling.Ignore)]
        public string GatewayResultMessage { get; set; }

        /// <summary>
        /// Gets or sets ThreeDSRedirect.
        /// </summary>
        [JsonProperty("ThreeDSRedirect", NullValueHandling = NullValueHandling.Ignore)]
        public Models.ThreeDsRedirectDataV3 ThreeDSRedirect { get; set; }

        /// <summary>
        /// Gets or sets CAVV.
        /// </summary>
        [JsonProperty("CAVV", NullValueHandling = NullValueHandling.Ignore)]
        public string CAVV { get; set; }

        /// <summary>
        /// Gets or sets ECI.
        /// </summary>
        [JsonProperty("ECI", NullValueHandling = NullValueHandling.Ignore)]
        public string ECI { get; set; }

        /// <summary>
        /// Gets or sets GatewaySourceResponse.
        /// </summary>
        [JsonProperty("GatewaySourceResponse", NullValueHandling = NullValueHandling.Ignore)]
        public string GatewaySourceResponse { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"AuthorizationModel : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is AuthorizationModel other &&
                (this.Status.Equals(other.Status)) &&
                (this.Date == null && other.Date == null ||
                 this.Date?.Equals(other.Date) == true) &&
                (this.SplititErrorResultCode == null && other.SplititErrorResultCode == null ||
                 this.SplititErrorResultCode?.Equals(other.SplititErrorResultCode) == true) &&
                (this.GatewayTransactionID == null && other.GatewayTransactionID == null ||
                 this.GatewayTransactionID?.Equals(other.GatewayTransactionID) == true) &&
                (this.GatewayResultCode == null && other.GatewayResultCode == null ||
                 this.GatewayResultCode?.Equals(other.GatewayResultCode) == true) &&
                (this.GatewayResultMessage == null && other.GatewayResultMessage == null ||
                 this.GatewayResultMessage?.Equals(other.GatewayResultMessage) == true) &&
                (this.ThreeDSRedirect == null && other.ThreeDSRedirect == null ||
                 this.ThreeDSRedirect?.Equals(other.ThreeDSRedirect) == true) &&
                (this.CAVV == null && other.CAVV == null ||
                 this.CAVV?.Equals(other.CAVV) == true) &&
                (this.ECI == null && other.ECI == null ||
                 this.ECI?.Equals(other.ECI) == true) &&
                (this.GatewaySourceResponse == null && other.GatewaySourceResponse == null ||
                 this.GatewaySourceResponse?.Equals(other.GatewaySourceResponse) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Status = {this.Status}");
            toStringOutput.Add($"Date = {(this.Date == null ? "null" : this.Date.ToString())}");
            toStringOutput.Add($"SplititErrorResultCode = {this.SplititErrorResultCode ?? "null"}");
            toStringOutput.Add($"GatewayTransactionID = {this.GatewayTransactionID ?? "null"}");
            toStringOutput.Add($"GatewayResultCode = {this.GatewayResultCode ?? "null"}");
            toStringOutput.Add($"GatewayResultMessage = {this.GatewayResultMessage ?? "null"}");
            toStringOutput.Add($"ThreeDSRedirect = {(this.ThreeDSRedirect == null ? "null" : this.ThreeDSRedirect.ToString())}");
            toStringOutput.Add($"CAVV = {this.CAVV ?? "null"}");
            toStringOutput.Add($"ECI = {this.ECI ?? "null"}");
            toStringOutput.Add($"GatewaySourceResponse = {this.GatewaySourceResponse ?? "null"}");
        }
    }
}