// <copyright file="CardTypeEnum.cs" company="APIMatic">
// SplititWebApiV3.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using SplititWebApiV3.Standard;
using SplititWebApiV3.Standard.Utilities;

namespace SplititWebApiV3.Standard.Models
{
    /// <summary>
    /// CardTypeEnum.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum CardTypeEnum
    {
        /// <summary>
        /// Credit.
        /// </summary>
        [EnumMember(Value = "Credit")]
        Credit,

        /// <summary>
        /// Debit.
        /// </summary>
        [EnumMember(Value = "Debit")]
        Debit,

        /// <summary>
        /// Charge.
        /// </summary>
        [EnumMember(Value = "Charge")]
        Charge,

        /// <summary>
        /// Other.
        /// </summary>
        [EnumMember(Value = "Other")]
        Other,

        /// <summary>
        /// Prepaid.
        /// </summary>
        [EnumMember(Value = "Prepaid")]
        Prepaid,

        /// <summary>
        /// VisaDeferredDebit.
        /// </summary>
        [EnumMember(Value = "VisaDeferredDebit")]
        VisaDeferredDebit,

        /// <summary>
        /// NetworkOnly.
        /// </summary>
        [EnumMember(Value = "NetworkOnly")]
        NetworkOnly
    }
}