// <copyright file="CardData.cs" company="APIMatic">
// SplititWebApiV3.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SplititWebApiV3.Standard;
using SplititWebApiV3.Standard.Utilities;

namespace SplititWebApiV3.Standard.Models
{
    /// <summary>
    /// CardData.
    /// </summary>
    public class CardData
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CardData"/> class.
        /// </summary>
        public CardData()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="CardData"/> class.
        /// </summary>
        /// <param name="cardHolderFullName">CardHolderFullName.</param>
        /// <param name="cardNumber">CardNumber.</param>
        /// <param name="cardExpYear">CardExpYear.</param>
        /// <param name="cardExpMonth">CardExpMonth.</param>
        /// <param name="cardCvv">CardCvv.</param>
        /// <param name="cardBrand">CardBrand.</param>
        /// <param name="cardType">CardType.</param>
        public CardData(
            string cardHolderFullName = "",
            string cardNumber = "",
            string cardExpYear = "",
            string cardExpMonth = "",
            string cardCvv = "",
            Models.CardBrandEnum? cardBrand = null,
            Models.CardTypeEnum? cardType = null)
        {
            this.CardHolderFullName = cardHolderFullName;
            this.CardNumber = cardNumber;
            this.CardExpYear = cardExpYear;
            this.CardExpMonth = cardExpMonth;
            this.CardCvv = cardCvv;
            this.CardBrand = cardBrand;
            this.CardType = cardType;
        }

        /// <summary>
        /// Gets or sets CardHolderFullName.
        /// </summary>
        [JsonProperty("CardHolderFullName", NullValueHandling = NullValueHandling.Ignore)]
        public string CardHolderFullName { get; set; }

        /// <summary>
        /// Gets or sets CardNumber.
        /// </summary>
        [JsonProperty("CardNumber", NullValueHandling = NullValueHandling.Ignore)]
        public string CardNumber { get; set; }

        /// <summary>
        /// Gets or sets CardExpYear.
        /// </summary>
        [JsonProperty("CardExpYear", NullValueHandling = NullValueHandling.Ignore)]
        public string CardExpYear { get; set; }

        /// <summary>
        /// Gets or sets CardExpMonth.
        /// </summary>
        [JsonProperty("CardExpMonth", NullValueHandling = NullValueHandling.Ignore)]
        public string CardExpMonth { get; set; }

        /// <summary>
        /// Gets or sets CardCvv.
        /// </summary>
        [JsonProperty("CardCvv", NullValueHandling = NullValueHandling.Ignore)]
        public string CardCvv { get; set; }

        /// <summary>
        /// Gets or sets CardBrand.
        /// </summary>
        [JsonProperty("CardBrand", NullValueHandling = NullValueHandling.Ignore)]
        public Models.CardBrandEnum? CardBrand { get; set; }

        /// <summary>
        /// Gets or sets CardType.
        /// </summary>
        [JsonProperty("CardType", NullValueHandling = NullValueHandling.Ignore)]
        public Models.CardTypeEnum? CardType { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"CardData : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is CardData other &&
                (this.CardHolderFullName == null && other.CardHolderFullName == null ||
                 this.CardHolderFullName?.Equals(other.CardHolderFullName) == true) &&
                (this.CardNumber == null && other.CardNumber == null ||
                 this.CardNumber?.Equals(other.CardNumber) == true) &&
                (this.CardExpYear == null && other.CardExpYear == null ||
                 this.CardExpYear?.Equals(other.CardExpYear) == true) &&
                (this.CardExpMonth == null && other.CardExpMonth == null ||
                 this.CardExpMonth?.Equals(other.CardExpMonth) == true) &&
                (this.CardCvv == null && other.CardCvv == null ||
                 this.CardCvv?.Equals(other.CardCvv) == true) &&
                (this.CardBrand == null && other.CardBrand == null ||
                 this.CardBrand?.Equals(other.CardBrand) == true) &&
                (this.CardType == null && other.CardType == null ||
                 this.CardType?.Equals(other.CardType) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"CardHolderFullName = {this.CardHolderFullName ?? "null"}");
            toStringOutput.Add($"CardNumber = {this.CardNumber ?? "null"}");
            toStringOutput.Add($"CardExpYear = {this.CardExpYear ?? "null"}");
            toStringOutput.Add($"CardExpMonth = {this.CardExpMonth ?? "null"}");
            toStringOutput.Add($"CardCvv = {this.CardCvv ?? "null"}");
            toStringOutput.Add($"CardBrand = {(this.CardBrand == null ? "null" : this.CardBrand.ToString())}");
            toStringOutput.Add($"CardType = {(this.CardType == null ? "null" : this.CardType.ToString())}");
        }
    }
}