// <copyright file="CardBrandEnum.cs" company="APIMatic">
// SplititWebApiV3.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using SplititWebApiV3.Standard;
using SplititWebApiV3.Standard.Utilities;

namespace SplititWebApiV3.Standard.Models
{
    /// <summary>
    /// CardBrandEnum.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum CardBrandEnum
    {
        /// <summary>
        /// Mastercard.
        /// </summary>
        [EnumMember(Value = "Mastercard")]
        Mastercard,

        /// <summary>
        /// Visa.
        /// </summary>
        [EnumMember(Value = "Visa")]
        Visa,

        /// <summary>
        /// AmericanExpress.
        /// </summary>
        [EnumMember(Value = "AmericanExpress")]
        AmericanExpress,

        /// <summary>
        /// Maestro.
        /// </summary>
        [EnumMember(Value = "Maestro")]
        Maestro,

        /// <summary>
        /// JCB.
        /// </summary>
        [EnumMember(Value = "JCB")]
        JCB,

        /// <summary>
        /// CUP.
        /// </summary>
        [EnumMember(Value = "CUP")]
        CUP,

        /// <summary>
        /// UPI.
        /// </summary>
        [EnumMember(Value = "UPI")]
        UPI,

        /// <summary>
        /// Discover.
        /// </summary>
        [EnumMember(Value = "Discover")]
        Discover,

        /// <summary>
        /// Other.
        /// </summary>
        [EnumMember(Value = "Other")]
        Other
    }
}