// <copyright file="CheckInstallmentsEligibilityRequest.cs" company="APIMatic">
// SplititWebApiV3.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SplititWebApiV3.Standard;
using SplititWebApiV3.Standard.Utilities;

namespace SplititWebApiV3.Standard.Models
{
    /// <summary>
    /// CheckInstallmentsEligibilityRequest.
    /// </summary>
    public class CheckInstallmentsEligibilityRequest
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CheckInstallmentsEligibilityRequest"/> class.
        /// </summary>
        public CheckInstallmentsEligibilityRequest()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="CheckInstallmentsEligibilityRequest"/> class.
        /// </summary>
        /// <param name="planData">PlanData.</param>
        /// <param name="cardDetails">CardDetails.</param>
        /// <param name="billingAddress">BillingAddress.</param>
        /// <param name="shopperIdentifier">ShopperIdentifier.</param>
        public CheckInstallmentsEligibilityRequest(
            Models.PlanData planData = null,
            Models.CardData cardDetails = null,
            Models.AddressData billingAddress = null,
            string shopperIdentifier = "")
        {
            this.PlanData = planData;
            this.CardDetails = cardDetails;
            this.BillingAddress = billingAddress;
            this.ShopperIdentifier = shopperIdentifier;
        }

        /// <summary>
        /// Gets or sets PlanData.
        /// </summary>
        [JsonProperty("PlanData", NullValueHandling = NullValueHandling.Ignore)]
        public Models.PlanData PlanData { get; set; }

        /// <summary>
        /// Gets or sets CardDetails.
        /// </summary>
        [JsonProperty("CardDetails", NullValueHandling = NullValueHandling.Ignore)]
        public Models.CardData CardDetails { get; set; }

        /// <summary>
        /// Gets or sets BillingAddress.
        /// </summary>
        [JsonProperty("BillingAddress", NullValueHandling = NullValueHandling.Ignore)]
        public Models.AddressData BillingAddress { get; set; }

        /// <summary>
        /// Gets or sets ShopperIdentifier.
        /// </summary>
        [JsonProperty("ShopperIdentifier", NullValueHandling = NullValueHandling.Ignore)]
        public string ShopperIdentifier { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"CheckInstallmentsEligibilityRequest : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is CheckInstallmentsEligibilityRequest other &&
                (this.PlanData == null && other.PlanData == null ||
                 this.PlanData?.Equals(other.PlanData) == true) &&
                (this.CardDetails == null && other.CardDetails == null ||
                 this.CardDetails?.Equals(other.CardDetails) == true) &&
                (this.BillingAddress == null && other.BillingAddress == null ||
                 this.BillingAddress?.Equals(other.BillingAddress) == true) &&
                (this.ShopperIdentifier == null && other.ShopperIdentifier == null ||
                 this.ShopperIdentifier?.Equals(other.ShopperIdentifier) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"PlanData = {(this.PlanData == null ? "null" : this.PlanData.ToString())}");
            toStringOutput.Add($"CardDetails = {(this.CardDetails == null ? "null" : this.CardDetails.ToString())}");
            toStringOutput.Add($"BillingAddress = {(this.BillingAddress == null ? "null" : this.BillingAddress.ToString())}");
            toStringOutput.Add($"ShopperIdentifier = {this.ShopperIdentifier ?? "null"}");
        }
    }
}