// <copyright file="EligibilityTermsAndConditionResponse.cs" company="APIMatic">
// SplititWebApiV3.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SplititWebApiV3.Standard;
using SplititWebApiV3.Standard.Utilities;

namespace SplititWebApiV3.Standard.Models
{
    /// <summary>
    /// EligibilityTermsAndConditionResponse.
    /// </summary>
    public class EligibilityTermsAndConditionResponse
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EligibilityTermsAndConditionResponse"/> class.
        /// </summary>
        public EligibilityTermsAndConditionResponse()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="EligibilityTermsAndConditionResponse"/> class.
        /// </summary>
        /// <param name="termsAndConditions">TermsAndConditions.</param>
        /// <param name="privacyPolicy">PrivacyPolicy.</param>
        /// <param name="provider">Provider.</param>
        public EligibilityTermsAndConditionResponse(
            string termsAndConditions = "",
            string privacyPolicy = "",
            string provider = "")
        {
            this.TermsAndConditions = termsAndConditions;
            this.PrivacyPolicy = privacyPolicy;
            this.Provider = provider;
        }

        /// <summary>
        /// Gets or sets TermsAndConditions.
        /// </summary>
        [JsonProperty("TermsAndConditions", NullValueHandling = NullValueHandling.Ignore)]
        public string TermsAndConditions { get; set; }

        /// <summary>
        /// Gets or sets PrivacyPolicy.
        /// </summary>
        [JsonProperty("PrivacyPolicy", NullValueHandling = NullValueHandling.Ignore)]
        public string PrivacyPolicy { get; set; }

        /// <summary>
        /// Gets or sets Provider.
        /// </summary>
        [JsonProperty("Provider", NullValueHandling = NullValueHandling.Ignore)]
        public string Provider { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"EligibilityTermsAndConditionResponse : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is EligibilityTermsAndConditionResponse other &&
                (this.TermsAndConditions == null && other.TermsAndConditions == null ||
                 this.TermsAndConditions?.Equals(other.TermsAndConditions) == true) &&
                (this.PrivacyPolicy == null && other.PrivacyPolicy == null ||
                 this.PrivacyPolicy?.Equals(other.PrivacyPolicy) == true) &&
                (this.Provider == null && other.Provider == null ||
                 this.Provider?.Equals(other.Provider) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"TermsAndConditions = {this.TermsAndConditions ?? "null"}");
            toStringOutput.Add($"PrivacyPolicy = {this.PrivacyPolicy ?? "null"}");
            toStringOutput.Add($"Provider = {this.Provider ?? "null"}");
        }
    }
}