// <copyright file="EventsEndpointsModel.cs" company="APIMatic">
// SplititWebApiV3.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SplititWebApiV3.Standard;
using SplititWebApiV3.Standard.Utilities;

namespace SplititWebApiV3.Standard.Models
{
    /// <summary>
    /// EventsEndpointsModel.
    /// </summary>
    public class EventsEndpointsModel
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EventsEndpointsModel"/> class.
        /// </summary>
        public EventsEndpointsModel()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="EventsEndpointsModel"/> class.
        /// </summary>
        /// <param name="createSucceeded">CreateSucceeded.</param>
        public EventsEndpointsModel(
            string createSucceeded = "")
        {
            this.CreateSucceeded = createSucceeded;
        }

        /// <summary>
        /// Gets or sets CreateSucceeded.
        /// </summary>
        [JsonProperty("CreateSucceeded", NullValueHandling = NullValueHandling.Ignore)]
        public string CreateSucceeded { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"EventsEndpointsModel : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is EventsEndpointsModel other &&
                (this.CreateSucceeded == null && other.CreateSucceeded == null ||
                 this.CreateSucceeded?.Equals(other.CreateSucceeded) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"CreateSucceeded = {this.CreateSucceeded ?? "null"}");
        }
    }
}