// <copyright file="GwAuthorizationStatusEnum.cs" company="APIMatic">
// SplititWebApiV3.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using SplititWebApiV3.Standard;
using SplititWebApiV3.Standard.Utilities;

namespace SplititWebApiV3.Standard.Models
{
    /// <summary>
    /// GwAuthorizationStatusEnum.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum GwAuthorizationStatusEnum
    {
        /// <summary>
        /// NA.
        /// </summary>
        [EnumMember(Value = "NA")]
        NA,

        /// <summary>
        /// Succeeded.
        /// </summary>
        [EnumMember(Value = "Succeeded")]
        Succeeded,

        /// <summary>
        /// Pending3DS.
        /// </summary>
        [EnumMember(Value = "Pending3DS")]
        Pending3DS,

        /// <summary>
        /// Failed.
        /// </summary>
        [EnumMember(Value = "Failed")]
        Failed,

        /// <summary>
        /// Canceled.
        /// </summary>
        [EnumMember(Value = "Canceled")]
        Canceled,

        /// <summary>
        /// Voided.
        /// </summary>
        [EnumMember(Value = "Voided")]
        Voided
    }
}