// <copyright file="IdentifierContract.cs" company="APIMatic">
// SplititWebApiV3.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SplititWebApiV3.Standard;
using SplititWebApiV3.Standard.Utilities;

namespace SplititWebApiV3.Standard.Models
{
    /// <summary>
    /// IdentifierContract.
    /// </summary>
    public class IdentifierContract
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="IdentifierContract"/> class.
        /// </summary>
        public IdentifierContract()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="IdentifierContract"/> class.
        /// </summary>
        /// <param name="refOrderNumber">RefOrderNumber.</param>
        /// <param name="installmentPlanNumber">InstallmentPlanNumber.</param>
        /// <param name="extendedParams">ExtendedParams.</param>
        public IdentifierContract(
            string refOrderNumber = "",
            string installmentPlanNumber = "",
            Dictionary<string, string> extendedParams = null)
        {
            this.RefOrderNumber = refOrderNumber;
            this.InstallmentPlanNumber = installmentPlanNumber;
            this.ExtendedParams = extendedParams;
        }

        /// <summary>
        /// Gets or sets RefOrderNumber.
        /// </summary>
        [JsonProperty("RefOrderNumber", NullValueHandling = NullValueHandling.Ignore)]
        public string RefOrderNumber { get; set; }

        /// <summary>
        /// Gets or sets InstallmentPlanNumber.
        /// </summary>
        [JsonProperty("InstallmentPlanNumber", NullValueHandling = NullValueHandling.Ignore)]
        public string InstallmentPlanNumber { get; set; }

        /// <summary>
        /// Gets or sets ExtendedParams.
        /// </summary>
        [JsonProperty("ExtendedParams", NullValueHandling = NullValueHandling.Ignore)]
        public Dictionary<string, string> ExtendedParams { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"IdentifierContract : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is IdentifierContract other &&
                (this.RefOrderNumber == null && other.RefOrderNumber == null ||
                 this.RefOrderNumber?.Equals(other.RefOrderNumber) == true) &&
                (this.InstallmentPlanNumber == null && other.InstallmentPlanNumber == null ||
                 this.InstallmentPlanNumber?.Equals(other.InstallmentPlanNumber) == true) &&
                (this.ExtendedParams == null && other.ExtendedParams == null ||
                 this.ExtendedParams?.Equals(other.ExtendedParams) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"RefOrderNumber = {this.RefOrderNumber ?? "null"}");
            toStringOutput.Add($"InstallmentPlanNumber = {this.InstallmentPlanNumber ?? "null"}");
            toStringOutput.Add($"ExtendedParams = {(this.ExtendedParams == null ? "null" : this.ExtendedParams.ToString())}");
        }
    }
}