// <copyright file="InitiatePlanResponse.cs" company="APIMatic">
// SplititWebApiV3.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SplititWebApiV3.Standard;
using SplititWebApiV3.Standard.Utilities;

namespace SplititWebApiV3.Standard.Models
{
    /// <summary>
    /// InitiatePlanResponse.
    /// </summary>
    public class InitiatePlanResponse
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="InitiatePlanResponse"/> class.
        /// </summary>
        public InitiatePlanResponse()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="InitiatePlanResponse"/> class.
        /// </summary>
        /// <param name="status">Status.</param>
        /// <param name="installmentPlanNumber">InstallmentPlanNumber.</param>
        /// <param name="refOrderNumber">RefOrderNumber.</param>
        /// <param name="purchaseMethod">PurchaseMethod.</param>
        /// <param name="currency">Currency.</param>
        /// <param name="amount">Amount.</param>
        /// <param name="extendedParams">ExtendedParams.</param>
        /// <param name="shopper">Shopper.</param>
        /// <param name="billingAddress">BillingAddress.</param>
        /// <param name="checkoutUrl">CheckoutUrl.</param>
        /// <param name="principalAmount">PrincipalAmount.</param>
        public InitiatePlanResponse(
            Models.PlanStatusEnum status,
            string installmentPlanNumber = "",
            string refOrderNumber = "",
            Models.PurchaseMethodEnum? purchaseMethod = null,
            string currency = "",
            double? amount = null,
            Dictionary<string, string> extendedParams = null,
            Models.ShopperData shopper = null,
            Models.AddressData billingAddress = null,
            string checkoutUrl = "",
            double? principalAmount = null)
        {
            this.InstallmentPlanNumber = installmentPlanNumber;
            this.RefOrderNumber = refOrderNumber;
            this.PurchaseMethod = purchaseMethod;
            this.Status = status;
            this.Currency = currency;
            this.Amount = amount;
            this.ExtendedParams = extendedParams;
            this.Shopper = shopper;
            this.BillingAddress = billingAddress;
            this.CheckoutUrl = checkoutUrl;
            this.PrincipalAmount = principalAmount;
        }

        /// <summary>
        /// Gets or sets InstallmentPlanNumber.
        /// </summary>
        [JsonProperty("InstallmentPlanNumber", NullValueHandling = NullValueHandling.Ignore)]
        public string InstallmentPlanNumber { get; set; }

        /// <summary>
        /// Gets or sets RefOrderNumber.
        /// </summary>
        [JsonProperty("RefOrderNumber", NullValueHandling = NullValueHandling.Ignore)]
        public string RefOrderNumber { get; set; }

        /// <summary>
        /// Gets or sets PurchaseMethod.
        /// </summary>
        [JsonProperty("PurchaseMethod", NullValueHandling = NullValueHandling.Ignore)]
        public Models.PurchaseMethodEnum? PurchaseMethod { get; set; }

        /// <summary>
        /// Gets or sets Status.
        /// </summary>
        [JsonProperty("Status")]
        public Models.PlanStatusEnum Status { get; set; }

        /// <summary>
        /// Gets or sets Currency.
        /// </summary>
        [JsonProperty("Currency", NullValueHandling = NullValueHandling.Ignore)]
        public string Currency { get; set; }

        /// <summary>
        /// Gets or sets Amount.
        /// </summary>
        [JsonProperty("Amount", NullValueHandling = NullValueHandling.Ignore)]
        public double? Amount { get; set; }

        /// <summary>
        /// Gets or sets ExtendedParams.
        /// </summary>
        [JsonProperty("ExtendedParams", NullValueHandling = NullValueHandling.Ignore)]
        public Dictionary<string, string> ExtendedParams { get; set; }

        /// <summary>
        /// Gets or sets Shopper.
        /// </summary>
        [JsonProperty("Shopper", NullValueHandling = NullValueHandling.Ignore)]
        public Models.ShopperData Shopper { get; set; }

        /// <summary>
        /// Gets or sets BillingAddress.
        /// </summary>
        [JsonProperty("BillingAddress", NullValueHandling = NullValueHandling.Ignore)]
        public Models.AddressData BillingAddress { get; set; }

        /// <summary>
        /// Gets or sets CheckoutUrl.
        /// </summary>
        [JsonProperty("CheckoutUrl", NullValueHandling = NullValueHandling.Ignore)]
        public string CheckoutUrl { get; set; }

        /// <summary>
        /// Gets or sets PrincipalAmount.
        /// </summary>
        [JsonProperty("PrincipalAmount", NullValueHandling = NullValueHandling.Ignore)]
        public double? PrincipalAmount { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"InitiatePlanResponse : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is InitiatePlanResponse other &&
                (this.InstallmentPlanNumber == null && other.InstallmentPlanNumber == null ||
                 this.InstallmentPlanNumber?.Equals(other.InstallmentPlanNumber) == true) &&
                (this.RefOrderNumber == null && other.RefOrderNumber == null ||
                 this.RefOrderNumber?.Equals(other.RefOrderNumber) == true) &&
                (this.PurchaseMethod == null && other.PurchaseMethod == null ||
                 this.PurchaseMethod?.Equals(other.PurchaseMethod) == true) &&
                (this.Status.Equals(other.Status)) &&
                (this.Currency == null && other.Currency == null ||
                 this.Currency?.Equals(other.Currency) == true) &&
                (this.Amount == null && other.Amount == null ||
                 this.Amount?.Equals(other.Amount) == true) &&
                (this.ExtendedParams == null && other.ExtendedParams == null ||
                 this.ExtendedParams?.Equals(other.ExtendedParams) == true) &&
                (this.Shopper == null && other.Shopper == null ||
                 this.Shopper?.Equals(other.Shopper) == true) &&
                (this.BillingAddress == null && other.BillingAddress == null ||
                 this.BillingAddress?.Equals(other.BillingAddress) == true) &&
                (this.CheckoutUrl == null && other.CheckoutUrl == null ||
                 this.CheckoutUrl?.Equals(other.CheckoutUrl) == true) &&
                (this.PrincipalAmount == null && other.PrincipalAmount == null ||
                 this.PrincipalAmount?.Equals(other.PrincipalAmount) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"InstallmentPlanNumber = {this.InstallmentPlanNumber ?? "null"}");
            toStringOutput.Add($"RefOrderNumber = {this.RefOrderNumber ?? "null"}");
            toStringOutput.Add($"PurchaseMethod = {(this.PurchaseMethod == null ? "null" : this.PurchaseMethod.ToString())}");
            toStringOutput.Add($"Status = {this.Status}");
            toStringOutput.Add($"Currency = {this.Currency ?? "null"}");
            toStringOutput.Add($"Amount = {(this.Amount == null ? "null" : this.Amount.ToString())}");
            toStringOutput.Add($"ExtendedParams = {(this.ExtendedParams == null ? "null" : this.ExtendedParams.ToString())}");
            toStringOutput.Add($"Shopper = {(this.Shopper == null ? "null" : this.Shopper.ToString())}");
            toStringOutput.Add($"BillingAddress = {(this.BillingAddress == null ? "null" : this.BillingAddress.ToString())}");
            toStringOutput.Add($"CheckoutUrl = {this.CheckoutUrl ?? "null"}");
            toStringOutput.Add($"PrincipalAmount = {(this.PrincipalAmount == null ? "null" : this.PrincipalAmount.ToString())}");
        }
    }
}