// <copyright file="InstallmentPlanRefundResponse.cs" company="APIMatic">
// SplititWebApiV3.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SplititWebApiV3.Standard;
using SplititWebApiV3.Standard.Utilities;

namespace SplititWebApiV3.Standard.Models
{
    /// <summary>
    /// InstallmentPlanRefundResponse.
    /// </summary>
    public class InstallmentPlanRefundResponse
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="InstallmentPlanRefundResponse"/> class.
        /// </summary>
        public InstallmentPlanRefundResponse()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="InstallmentPlanRefundResponse"/> class.
        /// </summary>
        /// <param name="refundId">RefundId.</param>
        /// <param name="installmentPlanNumber">InstallmentPlanNumber.</param>
        /// <param name="currency">Currency.</param>
        /// <param name="nonCreditRefundAmount">NonCreditRefundAmount.</param>
        /// <param name="creditRefundAmount">CreditRefundAmount.</param>
        /// <param name="summary">Summary.</param>
        /// <param name="referenceId">ReferenceId.</param>
        public InstallmentPlanRefundResponse(
            string refundId = "",
            string installmentPlanNumber = "",
            string currency = "",
            double? nonCreditRefundAmount = null,
            double? creditRefundAmount = null,
            Models.RefundSummary summary = null,
            string referenceId = "")
        {
            this.RefundId = refundId;
            this.InstallmentPlanNumber = installmentPlanNumber;
            this.Currency = currency;
            this.NonCreditRefundAmount = nonCreditRefundAmount;
            this.CreditRefundAmount = creditRefundAmount;
            this.Summary = summary;
            this.ReferenceId = referenceId;
        }

        /// <summary>
        /// Gets or sets RefundId.
        /// </summary>
        [JsonProperty("RefundId", NullValueHandling = NullValueHandling.Ignore)]
        public string RefundId { get; set; }

        /// <summary>
        /// Gets or sets InstallmentPlanNumber.
        /// </summary>
        [JsonProperty("InstallmentPlanNumber", NullValueHandling = NullValueHandling.Ignore)]
        public string InstallmentPlanNumber { get; set; }

        /// <summary>
        /// Gets or sets Currency.
        /// </summary>
        [JsonProperty("Currency", NullValueHandling = NullValueHandling.Ignore)]
        public string Currency { get; set; }

        /// <summary>
        /// Gets or sets NonCreditRefundAmount.
        /// </summary>
        [JsonProperty("NonCreditRefundAmount", NullValueHandling = NullValueHandling.Ignore)]
        public double? NonCreditRefundAmount { get; set; }

        /// <summary>
        /// Gets or sets CreditRefundAmount.
        /// </summary>
        [JsonProperty("CreditRefundAmount", NullValueHandling = NullValueHandling.Ignore)]
        public double? CreditRefundAmount { get; set; }

        /// <summary>
        /// Gets or sets Summary.
        /// </summary>
        [JsonProperty("Summary", NullValueHandling = NullValueHandling.Ignore)]
        public Models.RefundSummary Summary { get; set; }

        /// <summary>
        /// Gets or sets ReferenceId.
        /// </summary>
        [JsonProperty("ReferenceId", NullValueHandling = NullValueHandling.Ignore)]
        public string ReferenceId { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"InstallmentPlanRefundResponse : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is InstallmentPlanRefundResponse other &&
                (this.RefundId == null && other.RefundId == null ||
                 this.RefundId?.Equals(other.RefundId) == true) &&
                (this.InstallmentPlanNumber == null && other.InstallmentPlanNumber == null ||
                 this.InstallmentPlanNumber?.Equals(other.InstallmentPlanNumber) == true) &&
                (this.Currency == null && other.Currency == null ||
                 this.Currency?.Equals(other.Currency) == true) &&
                (this.NonCreditRefundAmount == null && other.NonCreditRefundAmount == null ||
                 this.NonCreditRefundAmount?.Equals(other.NonCreditRefundAmount) == true) &&
                (this.CreditRefundAmount == null && other.CreditRefundAmount == null ||
                 this.CreditRefundAmount?.Equals(other.CreditRefundAmount) == true) &&
                (this.Summary == null && other.Summary == null ||
                 this.Summary?.Equals(other.Summary) == true) &&
                (this.ReferenceId == null && other.ReferenceId == null ||
                 this.ReferenceId?.Equals(other.ReferenceId) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"RefundId = {this.RefundId ?? "null"}");
            toStringOutput.Add($"InstallmentPlanNumber = {this.InstallmentPlanNumber ?? "null"}");
            toStringOutput.Add($"Currency = {this.Currency ?? "null"}");
            toStringOutput.Add($"NonCreditRefundAmount = {(this.NonCreditRefundAmount == null ? "null" : this.NonCreditRefundAmount.ToString())}");
            toStringOutput.Add($"CreditRefundAmount = {(this.CreditRefundAmount == null ? "null" : this.CreditRefundAmount.ToString())}");
            toStringOutput.Add($"Summary = {(this.Summary == null ? "null" : this.Summary.ToString())}");
            toStringOutput.Add($"ReferenceId = {this.ReferenceId ?? "null"}");
        }
    }
}