// <copyright file="InstallmentPlanRefundRequest.cs" company="APIMatic">
// SplititWebApiV3.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SplititWebApiV3.Standard;
using SplititWebApiV3.Standard.Utilities;

namespace SplititWebApiV3.Standard.Models
{
    /// <summary>
    /// InstallmentPlanRefundRequest.
    /// </summary>
    public class InstallmentPlanRefundRequest
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="InstallmentPlanRefundRequest"/> class.
        /// </summary>
        public InstallmentPlanRefundRequest()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="InstallmentPlanRefundRequest"/> class.
        /// </summary>
        /// <param name="amount">Amount.</param>
        /// <param name="refundStrategy">RefundStrategy.</param>
        /// <param name="referenceId">ReferenceId.</param>
        public InstallmentPlanRefundRequest(
            string amount,
            Models.RefundStrategyEnum? refundStrategy = null,
            string referenceId = "")
        {
            this.Amount = amount;
            this.RefundStrategy = refundStrategy;
            this.ReferenceId = referenceId;
        }

        /// <summary>
        /// Gets or sets Amount.
        /// </summary>
        [JsonProperty("Amount")]
        public string Amount { get; set; }

        /// <summary>
        /// Gets or sets RefundStrategy.
        /// </summary>
        [JsonProperty("RefundStrategy", NullValueHandling = NullValueHandling.Ignore)]
        public Models.RefundStrategyEnum? RefundStrategy { get; set; }

        /// <summary>
        /// Gets or sets ReferenceId.
        /// </summary>
        [JsonProperty("ReferenceId", NullValueHandling = NullValueHandling.Ignore)]
        public string ReferenceId { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"InstallmentPlanRefundRequest : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is InstallmentPlanRefundRequest other &&
                (this.Amount == null && other.Amount == null ||
                 this.Amount?.Equals(other.Amount) == true) &&
                (this.RefundStrategy == null && other.RefundStrategy == null ||
                 this.RefundStrategy?.Equals(other.RefundStrategy) == true) &&
                (this.ReferenceId == null && other.ReferenceId == null ||
                 this.ReferenceId?.Equals(other.ReferenceId) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Amount = {this.Amount ?? "null"}");
            toStringOutput.Add($"RefundStrategy = {(this.RefundStrategy == null ? "null" : this.RefundStrategy.ToString())}");
            toStringOutput.Add($"ReferenceId = {this.ReferenceId ?? "null"}");
        }
    }
}