// <copyright file="InstallmentsEligibilityResponse.cs" company="APIMatic">
// SplititWebApiV3.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SplititWebApiV3.Standard;
using SplititWebApiV3.Standard.Utilities;

namespace SplititWebApiV3.Standard.Models
{
    /// <summary>
    /// InstallmentsEligibilityResponse.
    /// </summary>
    public class InstallmentsEligibilityResponse
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="InstallmentsEligibilityResponse"/> class.
        /// </summary>
        public InstallmentsEligibilityResponse()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="InstallmentsEligibilityResponse"/> class.
        /// </summary>
        /// <param name="installmentProvider">InstallmentProvider.</param>
        /// <param name="paymentPlanOptions">PaymentPlanOptions.</param>
        public InstallmentsEligibilityResponse(
            string installmentProvider = "",
            List<Models.PaymentPlanOptionModel> paymentPlanOptions = null)
        {
            this.InstallmentProvider = installmentProvider;
            this.PaymentPlanOptions = paymentPlanOptions;
        }

        /// <summary>
        /// Gets or sets InstallmentProvider.
        /// </summary>
        [JsonProperty("InstallmentProvider", NullValueHandling = NullValueHandling.Ignore)]
        public string InstallmentProvider { get; set; }

        /// <summary>
        /// Gets or sets PaymentPlanOptions.
        /// </summary>
        [JsonProperty("PaymentPlanOptions", NullValueHandling = NullValueHandling.Ignore)]
        public List<Models.PaymentPlanOptionModel> PaymentPlanOptions { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"InstallmentsEligibilityResponse : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is InstallmentsEligibilityResponse other &&
                (this.InstallmentProvider == null && other.InstallmentProvider == null ||
                 this.InstallmentProvider?.Equals(other.InstallmentProvider) == true) &&
                (this.PaymentPlanOptions == null && other.PaymentPlanOptions == null ||
                 this.PaymentPlanOptions?.Equals(other.PaymentPlanOptions) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"InstallmentProvider = {this.InstallmentProvider ?? "null"}");
            toStringOutput.Add($"PaymentPlanOptions = {(this.PaymentPlanOptions == null ? "null" : $"[{string.Join(", ", this.PaymentPlanOptions)} ]")}");
        }
    }
}