// <copyright file="InstallmentPlanUpdateResponse.cs" company="APIMatic">
// SplititWebApiV3.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SplititWebApiV3.Standard;
using SplititWebApiV3.Standard.Utilities;

namespace SplititWebApiV3.Standard.Models
{
    /// <summary>
    /// InstallmentPlanUpdateResponse.
    /// </summary>
    public class InstallmentPlanUpdateResponse
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="InstallmentPlanUpdateResponse"/> class.
        /// </summary>
        public InstallmentPlanUpdateResponse()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="InstallmentPlanUpdateResponse"/> class.
        /// </summary>
        /// <param name="status">Status.</param>
        /// <param name="shippingStatus">ShippingStatus.</param>
        /// <param name="refOrderNumber">RefOrderNumber.</param>
        /// <param name="installmentPlanNumber">InstallmentPlanNumber.</param>
        /// <param name="newAmount">NewAmount.</param>
        public InstallmentPlanUpdateResponse(
            Models.PlanStatusEnum status,
            Models.ShippingStatusEnum shippingStatus,
            string refOrderNumber = "",
            string installmentPlanNumber = "",
            double? newAmount = null)
        {
            this.RefOrderNumber = refOrderNumber;
            this.InstallmentPlanNumber = installmentPlanNumber;
            this.Status = status;
            this.ShippingStatus = shippingStatus;
            this.NewAmount = newAmount;
        }

        /// <summary>
        /// Gets or sets RefOrderNumber.
        /// </summary>
        [JsonProperty("RefOrderNumber", NullValueHandling = NullValueHandling.Ignore)]
        public string RefOrderNumber { get; set; }

        /// <summary>
        /// Gets or sets InstallmentPlanNumber.
        /// </summary>
        [JsonProperty("InstallmentPlanNumber", NullValueHandling = NullValueHandling.Ignore)]
        public string InstallmentPlanNumber { get; set; }

        /// <summary>
        /// Gets or sets Status.
        /// </summary>
        [JsonProperty("Status")]
        public Models.PlanStatusEnum Status { get; set; }

        /// <summary>
        /// Gets or sets ShippingStatus.
        /// </summary>
        [JsonProperty("ShippingStatus")]
        public Models.ShippingStatusEnum ShippingStatus { get; set; }

        /// <summary>
        /// Gets or sets NewAmount.
        /// </summary>
        [JsonProperty("NewAmount", NullValueHandling = NullValueHandling.Ignore)]
        public double? NewAmount { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"InstallmentPlanUpdateResponse : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is InstallmentPlanUpdateResponse other &&
                (this.RefOrderNumber == null && other.RefOrderNumber == null ||
                 this.RefOrderNumber?.Equals(other.RefOrderNumber) == true) &&
                (this.InstallmentPlanNumber == null && other.InstallmentPlanNumber == null ||
                 this.InstallmentPlanNumber?.Equals(other.InstallmentPlanNumber) == true) &&
                (this.Status.Equals(other.Status)) &&
                (this.ShippingStatus.Equals(other.ShippingStatus)) &&
                (this.NewAmount == null && other.NewAmount == null ||
                 this.NewAmount?.Equals(other.NewAmount) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"RefOrderNumber = {this.RefOrderNumber ?? "null"}");
            toStringOutput.Add($"InstallmentPlanNumber = {this.InstallmentPlanNumber ?? "null"}");
            toStringOutput.Add($"Status = {this.Status}");
            toStringOutput.Add($"ShippingStatus = {this.ShippingStatus}");
            toStringOutput.Add($"NewAmount = {(this.NewAmount == null ? "null" : this.NewAmount.ToString())}");
        }
    }
}