// <copyright file="InstallmentPlanInitiateRequest.cs" company="APIMatic">
// SplititWebApiV3.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SplititWebApiV3.Standard;
using SplititWebApiV3.Standard.Utilities;

namespace SplititWebApiV3.Standard.Models
{
    /// <summary>
    /// InstallmentPlanInitiateRequest.
    /// </summary>
    public class InstallmentPlanInitiateRequest
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="InstallmentPlanInitiateRequest"/> class.
        /// </summary>
        public InstallmentPlanInitiateRequest()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="InstallmentPlanInitiateRequest"/> class.
        /// </summary>
        /// <param name="autoCapture">AutoCapture.</param>
        /// <param name="attempt3dSecure">Attempt3dSecure.</param>
        /// <param name="shopper">Shopper.</param>
        /// <param name="planData">PlanData.</param>
        /// <param name="billingAddress">BillingAddress.</param>
        /// <param name="redirectUrls">RedirectUrls.</param>
        /// <param name="uxSettings">UxSettings.</param>
        /// <param name="eventsEndpoints">EventsEndpoints.</param>
        /// <param name="processingData">ProcessingData.</param>
        public InstallmentPlanInitiateRequest(
            bool? autoCapture = false,
            bool? attempt3dSecure = false,
            Models.ShopperData shopper = null,
            Models.PlanDataModel planData = null,
            Models.AddressDataModel billingAddress = null,
            Models.InitiateRedirectionEndpointsModel redirectUrls = null,
            Models.UxSettingsModel uxSettings = null,
            Models.EventsEndpointsModel eventsEndpoints = null,
            Models.ProcessingData processingData = null)
        {
            this.AutoCapture = autoCapture;
            this.Attempt3dSecure = attempt3dSecure;
            this.Shopper = shopper;
            this.PlanData = planData;
            this.BillingAddress = billingAddress;
            this.RedirectUrls = redirectUrls;
            this.UxSettings = uxSettings;
            this.EventsEndpoints = eventsEndpoints;
            this.ProcessingData = processingData;
        }

        /// <summary>
        /// Gets or sets AutoCapture.
        /// </summary>
        [JsonProperty("AutoCapture", NullValueHandling = NullValueHandling.Ignore)]
        public bool? AutoCapture { get; set; }

        /// <summary>
        /// Gets or sets Attempt3dSecure.
        /// </summary>
        [JsonProperty("Attempt3dSecure", NullValueHandling = NullValueHandling.Ignore)]
        public bool? Attempt3dSecure { get; set; }

        /// <summary>
        /// Gets or sets Shopper.
        /// </summary>
        [JsonProperty("Shopper", NullValueHandling = NullValueHandling.Ignore)]
        public Models.ShopperData Shopper { get; set; }

        /// <summary>
        /// Gets or sets PlanData.
        /// </summary>
        [JsonProperty("PlanData", NullValueHandling = NullValueHandling.Ignore)]
        public Models.PlanDataModel PlanData { get; set; }

        /// <summary>
        /// Gets or sets BillingAddress.
        /// </summary>
        [JsonProperty("BillingAddress", NullValueHandling = NullValueHandling.Ignore)]
        public Models.AddressDataModel BillingAddress { get; set; }

        /// <summary>
        /// Gets or sets RedirectUrls.
        /// </summary>
        [JsonProperty("RedirectUrls", NullValueHandling = NullValueHandling.Ignore)]
        public Models.InitiateRedirectionEndpointsModel RedirectUrls { get; set; }

        /// <summary>
        /// Gets or sets UxSettings.
        /// </summary>
        [JsonProperty("UxSettings", NullValueHandling = NullValueHandling.Ignore)]
        public Models.UxSettingsModel UxSettings { get; set; }

        /// <summary>
        /// Gets or sets EventsEndpoints.
        /// </summary>
        [JsonProperty("EventsEndpoints", NullValueHandling = NullValueHandling.Ignore)]
        public Models.EventsEndpointsModel EventsEndpoints { get; set; }

        /// <summary>
        /// Gets or sets ProcessingData.
        /// </summary>
        [JsonProperty("ProcessingData", NullValueHandling = NullValueHandling.Ignore)]
        public Models.ProcessingData ProcessingData { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"InstallmentPlanInitiateRequest : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is InstallmentPlanInitiateRequest other &&
                (this.AutoCapture == null && other.AutoCapture == null ||
                 this.AutoCapture?.Equals(other.AutoCapture) == true) &&
                (this.Attempt3dSecure == null && other.Attempt3dSecure == null ||
                 this.Attempt3dSecure?.Equals(other.Attempt3dSecure) == true) &&
                (this.Shopper == null && other.Shopper == null ||
                 this.Shopper?.Equals(other.Shopper) == true) &&
                (this.PlanData == null && other.PlanData == null ||
                 this.PlanData?.Equals(other.PlanData) == true) &&
                (this.BillingAddress == null && other.BillingAddress == null ||
                 this.BillingAddress?.Equals(other.BillingAddress) == true) &&
                (this.RedirectUrls == null && other.RedirectUrls == null ||
                 this.RedirectUrls?.Equals(other.RedirectUrls) == true) &&
                (this.UxSettings == null && other.UxSettings == null ||
                 this.UxSettings?.Equals(other.UxSettings) == true) &&
                (this.EventsEndpoints == null && other.EventsEndpoints == null ||
                 this.EventsEndpoints?.Equals(other.EventsEndpoints) == true) &&
                (this.ProcessingData == null && other.ProcessingData == null ||
                 this.ProcessingData?.Equals(other.ProcessingData) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"AutoCapture = {(this.AutoCapture == null ? "null" : this.AutoCapture.ToString())}");
            toStringOutput.Add($"Attempt3dSecure = {(this.Attempt3dSecure == null ? "null" : this.Attempt3dSecure.ToString())}");
            toStringOutput.Add($"Shopper = {(this.Shopper == null ? "null" : this.Shopper.ToString())}");
            toStringOutput.Add($"PlanData = {(this.PlanData == null ? "null" : this.PlanData.ToString())}");
            toStringOutput.Add($"BillingAddress = {(this.BillingAddress == null ? "null" : this.BillingAddress.ToString())}");
            toStringOutput.Add($"RedirectUrls = {(this.RedirectUrls == null ? "null" : this.RedirectUrls.ToString())}");
            toStringOutput.Add($"UxSettings = {(this.UxSettings == null ? "null" : this.UxSettings.ToString())}");
            toStringOutput.Add($"EventsEndpoints = {(this.EventsEndpoints == null ? "null" : this.EventsEndpoints.ToString())}");
            toStringOutput.Add($"ProcessingData = {(this.ProcessingData == null ? "null" : this.ProcessingData.ToString())}");
        }
    }
}