// <copyright file="InstallmentPlanSearchResponse.cs" company="APIMatic">
// SplititWebApiV3.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SplititWebApiV3.Standard;
using SplititWebApiV3.Standard.Utilities;

namespace SplititWebApiV3.Standard.Models
{
    /// <summary>
    /// InstallmentPlanSearchResponse.
    /// </summary>
    public class InstallmentPlanSearchResponse
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="InstallmentPlanSearchResponse"/> class.
        /// </summary>
        public InstallmentPlanSearchResponse()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="InstallmentPlanSearchResponse"/> class.
        /// </summary>
        /// <param name="planList">PlanList.</param>
        public InstallmentPlanSearchResponse(
            List<Models.SearchInstallmentPlanResponseItem> planList = null)
        {
            this.PlanList = planList;
        }

        /// <summary>
        /// Gets or sets PlanList.
        /// </summary>
        [JsonProperty("PlanList", NullValueHandling = NullValueHandling.Ignore)]
        public List<Models.SearchInstallmentPlanResponseItem> PlanList { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"InstallmentPlanSearchResponse : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is InstallmentPlanSearchResponse other &&
                (this.PlanList == null && other.PlanList == null ||
                 this.PlanList?.Equals(other.PlanList) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"PlanList = {(this.PlanList == null ? "null" : $"[{string.Join(", ", this.PlanList)} ]")}");
        }
    }
}