// <copyright file="InstallmentPlanCreateRequest.cs" company="APIMatic">
// SplititWebApiV3.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SplititWebApiV3.Standard;
using SplititWebApiV3.Standard.Utilities;

namespace SplititWebApiV3.Standard.Models
{
    /// <summary>
    /// InstallmentPlanCreateRequest.
    /// </summary>
    public class InstallmentPlanCreateRequest
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="InstallmentPlanCreateRequest"/> class.
        /// </summary>
        public InstallmentPlanCreateRequest()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="InstallmentPlanCreateRequest"/> class.
        /// </summary>
        /// <param name="autoCapture">AutoCapture.</param>
        /// <param name="termsAndConditionsAccepted">TermsAndConditionsAccepted.</param>
        /// <param name="attempt3dSecure">Attempt3dSecure.</param>
        /// <param name="shopper">Shopper.</param>
        /// <param name="planData">PlanData.</param>
        /// <param name="billingAddress">BillingAddress.</param>
        /// <param name="paymentMethod">PaymentMethod.</param>
        /// <param name="redirectUrls">RedirectUrls.</param>
        /// <param name="processingData">ProcessingData.</param>
        /// <param name="eventsEndpoints">EventsEndpoints.</param>
        public InstallmentPlanCreateRequest(
            bool autoCapture,
            bool termsAndConditionsAccepted,
            bool? attempt3dSecure = false,
            Models.ShopperData shopper = null,
            Models.PlanDataModel planData = null,
            Models.AddressDataModel billingAddress = null,
            Models.PaymentMethodModel paymentMethod = null,
            Models.RedirectionEndpointsModel redirectUrls = null,
            Models.ProcessingData processingData = null,
            Models.EventsEndpointsModel eventsEndpoints = null)
        {
            this.AutoCapture = autoCapture;
            this.Attempt3dSecure = attempt3dSecure;
            this.TermsAndConditionsAccepted = termsAndConditionsAccepted;
            this.Shopper = shopper;
            this.PlanData = planData;
            this.BillingAddress = billingAddress;
            this.PaymentMethod = paymentMethod;
            this.RedirectUrls = redirectUrls;
            this.ProcessingData = processingData;
            this.EventsEndpoints = eventsEndpoints;
        }

        /// <summary>
        /// Gets or sets AutoCapture.
        /// </summary>
        [JsonProperty("AutoCapture")]
        public bool AutoCapture { get; set; }

        /// <summary>
        /// Gets or sets Attempt3dSecure.
        /// </summary>
        [JsonProperty("Attempt3dSecure", NullValueHandling = NullValueHandling.Ignore)]
        public bool? Attempt3dSecure { get; set; }

        /// <summary>
        /// Gets or sets TermsAndConditionsAccepted.
        /// </summary>
        [JsonProperty("TermsAndConditionsAccepted")]
        public bool TermsAndConditionsAccepted { get; set; }

        /// <summary>
        /// Gets or sets Shopper.
        /// </summary>
        [JsonProperty("Shopper", NullValueHandling = NullValueHandling.Ignore)]
        public Models.ShopperData Shopper { get; set; }

        /// <summary>
        /// Gets or sets PlanData.
        /// </summary>
        [JsonProperty("PlanData", NullValueHandling = NullValueHandling.Ignore)]
        public Models.PlanDataModel PlanData { get; set; }

        /// <summary>
        /// Gets or sets BillingAddress.
        /// </summary>
        [JsonProperty("BillingAddress", NullValueHandling = NullValueHandling.Ignore)]
        public Models.AddressDataModel BillingAddress { get; set; }

        /// <summary>
        /// Gets or sets PaymentMethod.
        /// </summary>
        [JsonProperty("PaymentMethod", NullValueHandling = NullValueHandling.Ignore)]
        public Models.PaymentMethodModel PaymentMethod { get; set; }

        /// <summary>
        /// Gets or sets RedirectUrls.
        /// </summary>
        [JsonProperty("RedirectUrls", NullValueHandling = NullValueHandling.Ignore)]
        public Models.RedirectionEndpointsModel RedirectUrls { get; set; }

        /// <summary>
        /// Gets or sets ProcessingData.
        /// </summary>
        [JsonProperty("ProcessingData", NullValueHandling = NullValueHandling.Ignore)]
        public Models.ProcessingData ProcessingData { get; set; }

        /// <summary>
        /// Gets or sets EventsEndpoints.
        /// </summary>
        [JsonProperty("EventsEndpoints", NullValueHandling = NullValueHandling.Ignore)]
        public Models.EventsEndpointsModel EventsEndpoints { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"InstallmentPlanCreateRequest : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is InstallmentPlanCreateRequest other &&
                (this.AutoCapture.Equals(other.AutoCapture)) &&
                (this.Attempt3dSecure == null && other.Attempt3dSecure == null ||
                 this.Attempt3dSecure?.Equals(other.Attempt3dSecure) == true) &&
                (this.TermsAndConditionsAccepted.Equals(other.TermsAndConditionsAccepted)) &&
                (this.Shopper == null && other.Shopper == null ||
                 this.Shopper?.Equals(other.Shopper) == true) &&
                (this.PlanData == null && other.PlanData == null ||
                 this.PlanData?.Equals(other.PlanData) == true) &&
                (this.BillingAddress == null && other.BillingAddress == null ||
                 this.BillingAddress?.Equals(other.BillingAddress) == true) &&
                (this.PaymentMethod == null && other.PaymentMethod == null ||
                 this.PaymentMethod?.Equals(other.PaymentMethod) == true) &&
                (this.RedirectUrls == null && other.RedirectUrls == null ||
                 this.RedirectUrls?.Equals(other.RedirectUrls) == true) &&
                (this.ProcessingData == null && other.ProcessingData == null ||
                 this.ProcessingData?.Equals(other.ProcessingData) == true) &&
                (this.EventsEndpoints == null && other.EventsEndpoints == null ||
                 this.EventsEndpoints?.Equals(other.EventsEndpoints) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"AutoCapture = {this.AutoCapture}");
            toStringOutput.Add($"Attempt3dSecure = {(this.Attempt3dSecure == null ? "null" : this.Attempt3dSecure.ToString())}");
            toStringOutput.Add($"TermsAndConditionsAccepted = {this.TermsAndConditionsAccepted}");
            toStringOutput.Add($"Shopper = {(this.Shopper == null ? "null" : this.Shopper.ToString())}");
            toStringOutput.Add($"PlanData = {(this.PlanData == null ? "null" : this.PlanData.ToString())}");
            toStringOutput.Add($"BillingAddress = {(this.BillingAddress == null ? "null" : this.BillingAddress.ToString())}");
            toStringOutput.Add($"PaymentMethod = {(this.PaymentMethod == null ? "null" : this.PaymentMethod.ToString())}");
            toStringOutput.Add($"RedirectUrls = {(this.RedirectUrls == null ? "null" : this.RedirectUrls.ToString())}");
            toStringOutput.Add($"ProcessingData = {(this.ProcessingData == null ? "null" : this.ProcessingData.ToString())}");
            toStringOutput.Add($"EventsEndpoints = {(this.EventsEndpoints == null ? "null" : this.EventsEndpoints.ToString())}");
        }
    }
}