// <copyright file="Installment.cs" company="APIMatic">
// SplititWebApiV3.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SplititWebApiV3.Standard;
using SplititWebApiV3.Standard.Utilities;

namespace SplititWebApiV3.Standard.Models
{
    /// <summary>
    /// Installment.
    /// </summary>
    public class Installment
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Installment"/> class.
        /// </summary>
        public Installment()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Installment"/> class.
        /// </summary>
        /// <param name="installmentNumber">InstallmentNumber.</param>
        /// <param name="amount">Amount.</param>
        /// <param name="status">Status.</param>
        /// <param name="processDateTime">ProcessDateTime.</param>
        public Installment(
            int installmentNumber,
            double amount,
            Models.InstallmentStatusEnum status,
            DateTime? processDateTime = null)
        {
            this.InstallmentNumber = installmentNumber;
            this.Amount = amount;
            this.ProcessDateTime = processDateTime;
            this.Status = status;
        }

        /// <summary>
        /// Gets or sets InstallmentNumber.
        /// </summary>
        [JsonProperty("InstallmentNumber")]
        public int InstallmentNumber { get; set; }

        /// <summary>
        /// Gets or sets Amount.
        /// </summary>
        [JsonProperty("Amount")]
        public double Amount { get; set; }

        /// <summary>
        /// Gets or sets ProcessDateTime.
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("ProcessDateTime", NullValueHandling = NullValueHandling.Ignore)]
        public DateTime? ProcessDateTime { get; set; }

        /// <summary>
        /// Gets or sets Status.
        /// </summary>
        [JsonProperty("Status")]
        public Models.InstallmentStatusEnum Status { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"Installment : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is Installment other &&
                (this.InstallmentNumber.Equals(other.InstallmentNumber)) &&
                (this.Amount.Equals(other.Amount)) &&
                (this.ProcessDateTime == null && other.ProcessDateTime == null ||
                 this.ProcessDateTime?.Equals(other.ProcessDateTime) == true) &&
                (this.Status.Equals(other.Status));
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"InstallmentNumber = {this.InstallmentNumber}");
            toStringOutput.Add($"Amount = {this.Amount}");
            toStringOutput.Add($"ProcessDateTime = {(this.ProcessDateTime == null ? "null" : this.ProcessDateTime.ToString())}");
            toStringOutput.Add($"Status = {this.Status}");
        }
    }
}