// <copyright file="InstallmentPlanUpdateRequestByIdentifier.cs" company="APIMatic">
// SplititWebApiV3.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SplititWebApiV3.Standard;
using SplititWebApiV3.Standard.Utilities;

namespace SplititWebApiV3.Standard.Models
{
    /// <summary>
    /// InstallmentPlanUpdateRequestByIdentifier.
    /// </summary>
    public class InstallmentPlanUpdateRequestByIdentifier
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="InstallmentPlanUpdateRequestByIdentifier"/> class.
        /// </summary>
        public InstallmentPlanUpdateRequestByIdentifier()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="InstallmentPlanUpdateRequestByIdentifier"/> class.
        /// </summary>
        /// <param name="refOrderNumber">RefOrderNumber.</param>
        /// <param name="trackingNumber">TrackingNumber.</param>
        /// <param name="capture">Capture.</param>
        /// <param name="shippingStatus">ShippingStatus.</param>
        /// <param name="newAmount">NewAmount.</param>
        /// <param name="identifier">Identifier.</param>
        public InstallmentPlanUpdateRequestByIdentifier(
            string refOrderNumber = "",
            string trackingNumber = "",
            bool? capture = false,
            Models.ShippingStatusEnum? shippingStatus = null,
            double? newAmount = null,
            Models.IdentifierContract identifier = null)
        {
            this.RefOrderNumber = refOrderNumber;
            this.TrackingNumber = trackingNumber;
            this.Capture = capture;
            this.ShippingStatus = shippingStatus;
            this.NewAmount = newAmount;
            this.Identifier = identifier;
        }

        /// <summary>
        /// Gets or sets RefOrderNumber.
        /// </summary>
        [JsonProperty("RefOrderNumber", NullValueHandling = NullValueHandling.Ignore)]
        public string RefOrderNumber { get; set; }

        /// <summary>
        /// Gets or sets TrackingNumber.
        /// </summary>
        [JsonProperty("TrackingNumber", NullValueHandling = NullValueHandling.Ignore)]
        public string TrackingNumber { get; set; }

        /// <summary>
        /// Gets or sets Capture.
        /// </summary>
        [JsonProperty("Capture", NullValueHandling = NullValueHandling.Ignore)]
        public bool? Capture { get; set; }

        /// <summary>
        /// Gets or sets ShippingStatus.
        /// </summary>
        [JsonProperty("ShippingStatus", NullValueHandling = NullValueHandling.Ignore)]
        public Models.ShippingStatusEnum? ShippingStatus { get; set; }

        /// <summary>
        /// Gets or sets NewAmount.
        /// </summary>
        [JsonProperty("NewAmount", NullValueHandling = NullValueHandling.Ignore)]
        public double? NewAmount { get; set; }

        /// <summary>
        /// Gets or sets Identifier.
        /// </summary>
        [JsonProperty("Identifier", NullValueHandling = NullValueHandling.Ignore)]
        public Models.IdentifierContract Identifier { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"InstallmentPlanUpdateRequestByIdentifier : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is InstallmentPlanUpdateRequestByIdentifier other &&
                (this.RefOrderNumber == null && other.RefOrderNumber == null ||
                 this.RefOrderNumber?.Equals(other.RefOrderNumber) == true) &&
                (this.TrackingNumber == null && other.TrackingNumber == null ||
                 this.TrackingNumber?.Equals(other.TrackingNumber) == true) &&
                (this.Capture == null && other.Capture == null ||
                 this.Capture?.Equals(other.Capture) == true) &&
                (this.ShippingStatus == null && other.ShippingStatus == null ||
                 this.ShippingStatus?.Equals(other.ShippingStatus) == true) &&
                (this.NewAmount == null && other.NewAmount == null ||
                 this.NewAmount?.Equals(other.NewAmount) == true) &&
                (this.Identifier == null && other.Identifier == null ||
                 this.Identifier?.Equals(other.Identifier) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"RefOrderNumber = {this.RefOrderNumber ?? "null"}");
            toStringOutput.Add($"TrackingNumber = {this.TrackingNumber ?? "null"}");
            toStringOutput.Add($"Capture = {(this.Capture == null ? "null" : this.Capture.ToString())}");
            toStringOutput.Add($"ShippingStatus = {(this.ShippingStatus == null ? "null" : this.ShippingStatus.ToString())}");
            toStringOutput.Add($"NewAmount = {(this.NewAmount == null ? "null" : this.NewAmount.ToString())}");
            toStringOutput.Add($"Identifier = {(this.Identifier == null ? "null" : this.Identifier.ToString())}");
        }
    }
}