// <copyright file="LinksModel.cs" company="APIMatic">
// SplititWebApiV3.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SplititWebApiV3.Standard;
using SplititWebApiV3.Standard.Utilities;

namespace SplititWebApiV3.Standard.Models
{
    /// <summary>
    /// LinksModel.
    /// </summary>
    public class LinksModel
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="LinksModel"/> class.
        /// </summary>
        public LinksModel()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="LinksModel"/> class.
        /// </summary>
        /// <param name="privacyPolicyUrl">PrivacyPolicyUrl.</param>
        /// <param name="termsAndConditionsUrl">TermsAndConditionsUrl.</param>
        /// <param name="learnMoreUrl">LearnMoreUrl.</param>
        public LinksModel(
            string privacyPolicyUrl = "",
            string termsAndConditionsUrl = "",
            string learnMoreUrl = "")
        {
            this.PrivacyPolicyUrl = privacyPolicyUrl;
            this.TermsAndConditionsUrl = termsAndConditionsUrl;
            this.LearnMoreUrl = learnMoreUrl;
        }

        /// <summary>
        /// Gets or sets PrivacyPolicyUrl.
        /// </summary>
        [JsonProperty("PrivacyPolicyUrl", NullValueHandling = NullValueHandling.Ignore)]
        public string PrivacyPolicyUrl { get; set; }

        /// <summary>
        /// Gets or sets TermsAndConditionsUrl.
        /// </summary>
        [JsonProperty("TermsAndConditionsUrl", NullValueHandling = NullValueHandling.Ignore)]
        public string TermsAndConditionsUrl { get; set; }

        /// <summary>
        /// Gets or sets LearnMoreUrl.
        /// </summary>
        [JsonProperty("LearnMoreUrl", NullValueHandling = NullValueHandling.Ignore)]
        public string LearnMoreUrl { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"LinksModel : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is LinksModel other &&
                (this.PrivacyPolicyUrl == null && other.PrivacyPolicyUrl == null ||
                 this.PrivacyPolicyUrl?.Equals(other.PrivacyPolicyUrl) == true) &&
                (this.TermsAndConditionsUrl == null && other.TermsAndConditionsUrl == null ||
                 this.TermsAndConditionsUrl?.Equals(other.TermsAndConditionsUrl) == true) &&
                (this.LearnMoreUrl == null && other.LearnMoreUrl == null ||
                 this.LearnMoreUrl?.Equals(other.LearnMoreUrl) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"PrivacyPolicyUrl = {this.PrivacyPolicyUrl ?? "null"}");
            toStringOutput.Add($"TermsAndConditionsUrl = {this.TermsAndConditionsUrl ?? "null"}");
            toStringOutput.Add($"LearnMoreUrl = {this.LearnMoreUrl ?? "null"}");
        }
    }
}