// <copyright file="LinksData.cs" company="APIMatic">
// SplititWebApiV3.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SplititWebApiV3.Standard;
using SplititWebApiV3.Standard.Utilities;

namespace SplititWebApiV3.Standard.Models
{
    /// <summary>
    /// LinksData.
    /// </summary>
    public class LinksData
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="LinksData"/> class.
        /// </summary>
        public LinksData()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="LinksData"/> class.
        /// </summary>
        /// <param name="checkout">Checkout.</param>
        /// <param name="learnMore">LearnMore.</param>
        /// <param name="termsConditions">TermsConditions.</param>
        /// <param name="privacyPolicy">PrivacyPolicy.</param>
        public LinksData(
            string checkout = "",
            string learnMore = "",
            string termsConditions = "",
            string privacyPolicy = "")
        {
            this.Checkout = checkout;
            this.LearnMore = learnMore;
            this.TermsConditions = termsConditions;
            this.PrivacyPolicy = privacyPolicy;
        }

        /// <summary>
        /// Gets or sets Checkout.
        /// </summary>
        [JsonProperty("Checkout", NullValueHandling = NullValueHandling.Ignore)]
        public string Checkout { get; set; }

        /// <summary>
        /// Gets or sets LearnMore.
        /// </summary>
        [JsonProperty("LearnMore", NullValueHandling = NullValueHandling.Ignore)]
        public string LearnMore { get; set; }

        /// <summary>
        /// Gets or sets TermsConditions.
        /// </summary>
        [JsonProperty("TermsConditions", NullValueHandling = NullValueHandling.Ignore)]
        public string TermsConditions { get; set; }

        /// <summary>
        /// Gets or sets PrivacyPolicy.
        /// </summary>
        [JsonProperty("PrivacyPolicy", NullValueHandling = NullValueHandling.Ignore)]
        public string PrivacyPolicy { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"LinksData : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is LinksData other &&
                (this.Checkout == null && other.Checkout == null ||
                 this.Checkout?.Equals(other.Checkout) == true) &&
                (this.LearnMore == null && other.LearnMore == null ||
                 this.LearnMore?.Equals(other.LearnMore) == true) &&
                (this.TermsConditions == null && other.TermsConditions == null ||
                 this.TermsConditions?.Equals(other.TermsConditions) == true) &&
                (this.PrivacyPolicy == null && other.PrivacyPolicy == null ||
                 this.PrivacyPolicy?.Equals(other.PrivacyPolicy) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Checkout = {this.Checkout ?? "null"}");
            toStringOutput.Add($"LearnMore = {this.LearnMore ?? "null"}");
            toStringOutput.Add($"TermsConditions = {this.TermsConditions ?? "null"}");
            toStringOutput.Add($"PrivacyPolicy = {this.PrivacyPolicy ?? "null"}");
        }
    }
}