// <copyright file="MockerShopperToken.cs" company="APIMatic">
// SplititWebApiV3.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SplititWebApiV3.Standard;
using SplititWebApiV3.Standard.Utilities;

namespace SplititWebApiV3.Standard.Models
{
    /// <summary>
    /// MockerShopperToken.
    /// </summary>
    public class MockerShopperToken
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MockerShopperToken"/> class.
        /// </summary>
        public MockerShopperToken()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="MockerShopperToken"/> class.
        /// </summary>
        /// <param name="token">Token.</param>
        /// <param name="last4Digit">Last4Digit.</param>
        public MockerShopperToken(
            string token = "",
            string last4Digit = "")
        {
            this.Token = token;
            this.Last4Digit = last4Digit;
        }

        /// <summary>
        /// Gets or sets Token.
        /// </summary>
        [JsonProperty("Token", NullValueHandling = NullValueHandling.Ignore)]
        public string Token { get; set; }

        /// <summary>
        /// Gets or sets Last4Digit.
        /// </summary>
        [JsonProperty("Last4Digit", NullValueHandling = NullValueHandling.Ignore)]
        public string Last4Digit { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"MockerShopperToken : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is MockerShopperToken other &&
                (this.Token == null && other.Token == null ||
                 this.Token?.Equals(other.Token) == true) &&
                (this.Last4Digit == null && other.Last4Digit == null ||
                 this.Last4Digit?.Equals(other.Last4Digit) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Token = {this.Token ?? "null"}");
            toStringOutput.Add($"Last4Digit = {this.Last4Digit ?? "null"}");
        }
    }
}