// <copyright file="OAuthScopeOAuth2ProductionEnum.cs" company="APIMatic">
// SplititWebApiV3.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using SplititWebApiV3.Standard;
using SplititWebApiV3.Standard.Utilities;
using System.Reflection;

namespace SplititWebApiV3.Standard.Models
{
    /// <summary>
    /// OAuthScopeOAuth2ProductionEnum.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum OAuthScopeOAuth2ProductionEnum
    {
        /// <summary>
        ///Access to WebAPI version 3
        /// ApiV3.
        /// </summary>
        [EnumMember(Value = "api.v3")]
        ApiV3
    }

    static class OAuthScopeOAuth2ProductionEnumExtention
    {
        internal static string GetValues(this IEnumerable<OAuthScopeOAuth2ProductionEnum> values)
        {
            return values != null ? string.Join(" ", values.Select(s => s.GetValue()).Where(s => !string.IsNullOrEmpty(s)).ToArray()) : null;
        }

        private static string GetValue(this Enum value)
        {
            return value.GetType()
                .GetTypeInfo()
                .DeclaredMembers
                .SingleOrDefault(x => x.Name == value.ToString())
                ?.GetCustomAttribute<EnumMemberAttribute>(false)
                ?.Value;
        }
    }
}