// <copyright file="PaymentMethodTypeEnum.cs" company="APIMatic">
// SplititWebApiV3.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using SplititWebApiV3.Standard;
using SplititWebApiV3.Standard.Utilities;

namespace SplititWebApiV3.Standard.Models
{
    /// <summary>
    /// PaymentMethodTypeEnum.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum PaymentMethodTypeEnum
    {
        /// <summary>
        /// Card.
        /// </summary>
        [EnumMember(Value = "Card")]
        Card,

        /// <summary>
        /// SplititToken.
        /// </summary>
        [EnumMember(Value = "SplititToken")]
        SplititToken,

        /// <summary>
        /// BluesnapVaultedShopperToken.
        /// </summary>
        [EnumMember(Value = "BluesnapVaultedShopperToken")]
        BluesnapVaultedShopperToken,

        /// <summary>
        /// SplititMockerV2Token.
        /// </summary>
        [EnumMember(Value = "SplititMockerV2Token")]
        SplititMockerV2Token,

        /// <summary>
        /// SpreedlyToken.
        /// </summary>
        [EnumMember(Value = "SpreedlyToken")]
        SpreedlyToken
    }
}