// <copyright file="PaymentMethodModel.cs" company="APIMatic">
// SplititWebApiV3.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SplititWebApiV3.Standard;
using SplititWebApiV3.Standard.Utilities;

namespace SplititWebApiV3.Standard.Models
{
    /// <summary>
    /// PaymentMethodModel.
    /// </summary>
    public class PaymentMethodModel
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PaymentMethodModel"/> class.
        /// </summary>
        public PaymentMethodModel()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PaymentMethodModel"/> class.
        /// </summary>
        /// <param name="type">Type.</param>
        /// <param name="card">Card.</param>
        /// <param name="token">Token.</param>
        /// <param name="bluesnapVaultedShopperToken">BluesnapVaultedShopperToken.</param>
        /// <param name="mockerShopperToken">MockerShopperToken.</param>
        /// <param name="spreedlyToken">SpreedlyToken.</param>
        /// <param name="cardPAR">CardPAR.</param>
        public PaymentMethodModel(
            Models.PaymentMethodTypeEnum type,
            Models.CardData card = null,
            string token = "",
            Models.BluesnapVaultedShopperToken bluesnapVaultedShopperToken = null,
            Models.MockerShopperToken mockerShopperToken = null,
            Models.SpreedlyToken spreedlyToken = null,
            string cardPAR = "")
        {
            this.Type = type;
            this.Card = card;
            this.Token = token;
            this.BluesnapVaultedShopperToken = bluesnapVaultedShopperToken;
            this.MockerShopperToken = mockerShopperToken;
            this.SpreedlyToken = spreedlyToken;
            this.CardPAR = cardPAR;
        }

        /// <summary>
        /// Gets or sets Type.
        /// </summary>
        [JsonProperty("Type")]
        public Models.PaymentMethodTypeEnum Type { get; set; }

        /// <summary>
        /// Gets or sets Card.
        /// </summary>
        [JsonProperty("Card", NullValueHandling = NullValueHandling.Ignore)]
        public Models.CardData Card { get; set; }

        /// <summary>
        /// Gets or sets Token.
        /// </summary>
        [JsonProperty("Token", NullValueHandling = NullValueHandling.Ignore)]
        public string Token { get; set; }

        /// <summary>
        /// Gets or sets BluesnapVaultedShopperToken.
        /// </summary>
        [JsonProperty("BluesnapVaultedShopperToken", NullValueHandling = NullValueHandling.Ignore)]
        public Models.BluesnapVaultedShopperToken BluesnapVaultedShopperToken { get; set; }

        /// <summary>
        /// Gets or sets MockerShopperToken.
        /// </summary>
        [JsonProperty("MockerShopperToken", NullValueHandling = NullValueHandling.Ignore)]
        public Models.MockerShopperToken MockerShopperToken { get; set; }

        /// <summary>
        /// Gets or sets SpreedlyToken.
        /// </summary>
        [JsonProperty("SpreedlyToken", NullValueHandling = NullValueHandling.Ignore)]
        public Models.SpreedlyToken SpreedlyToken { get; set; }

        /// <summary>
        /// Gets or sets CardPAR.
        /// </summary>
        [JsonProperty("CardPAR", NullValueHandling = NullValueHandling.Ignore)]
        public string CardPAR { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"PaymentMethodModel : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is PaymentMethodModel other &&
                (this.Type.Equals(other.Type)) &&
                (this.Card == null && other.Card == null ||
                 this.Card?.Equals(other.Card) == true) &&
                (this.Token == null && other.Token == null ||
                 this.Token?.Equals(other.Token) == true) &&
                (this.BluesnapVaultedShopperToken == null && other.BluesnapVaultedShopperToken == null ||
                 this.BluesnapVaultedShopperToken?.Equals(other.BluesnapVaultedShopperToken) == true) &&
                (this.MockerShopperToken == null && other.MockerShopperToken == null ||
                 this.MockerShopperToken?.Equals(other.MockerShopperToken) == true) &&
                (this.SpreedlyToken == null && other.SpreedlyToken == null ||
                 this.SpreedlyToken?.Equals(other.SpreedlyToken) == true) &&
                (this.CardPAR == null && other.CardPAR == null ||
                 this.CardPAR?.Equals(other.CardPAR) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Type = {this.Type}");
            toStringOutput.Add($"Card = {(this.Card == null ? "null" : this.Card.ToString())}");
            toStringOutput.Add($"Token = {this.Token ?? "null"}");
            toStringOutput.Add($"BluesnapVaultedShopperToken = {(this.BluesnapVaultedShopperToken == null ? "null" : this.BluesnapVaultedShopperToken.ToString())}");
            toStringOutput.Add($"MockerShopperToken = {(this.MockerShopperToken == null ? "null" : this.MockerShopperToken.ToString())}");
            toStringOutput.Add($"SpreedlyToken = {(this.SpreedlyToken == null ? "null" : this.SpreedlyToken.ToString())}");
            toStringOutput.Add($"CardPAR = {this.CardPAR ?? "null"}");
        }
    }
}