// <copyright file="PaymentPlanOptionModel.cs" company="APIMatic">
// SplititWebApiV3.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SplititWebApiV3.Standard;
using SplititWebApiV3.Standard.Utilities;

namespace SplititWebApiV3.Standard.Models
{
    /// <summary>
    /// PaymentPlanOptionModel.
    /// </summary>
    public class PaymentPlanOptionModel
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PaymentPlanOptionModel"/> class.
        /// </summary>
        public PaymentPlanOptionModel()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PaymentPlanOptionModel"/> class.
        /// </summary>
        /// <param name="numberOfInstallments">NumberOfInstallments.</param>
        /// <param name="firstInstallmentAmount">FirstInstallmentAmount.</param>
        /// <param name="installmentAmount">InstallmentAmount.</param>
        /// <param name="lastInstallmentAmount">LastInstallmentAmount.</param>
        /// <param name="links">Links.</param>
        /// <param name="termsAndConditionsBrief">TermsAndConditionsBrief.</param>
        /// <param name="installmentFrequency">InstallmentFrequency.</param>
        public PaymentPlanOptionModel(
            int numberOfInstallments,
            double firstInstallmentAmount,
            double installmentAmount,
            double lastInstallmentAmount,
            Models.LinksModel links = null,
            string termsAndConditionsBrief = "",
            string installmentFrequency = "")
        {
            this.NumberOfInstallments = numberOfInstallments;
            this.FirstInstallmentAmount = firstInstallmentAmount;
            this.InstallmentAmount = installmentAmount;
            this.LastInstallmentAmount = lastInstallmentAmount;
            this.Links = links;
            this.TermsAndConditionsBrief = termsAndConditionsBrief;
            this.InstallmentFrequency = installmentFrequency;
        }

        /// <summary>
        /// Gets or sets NumberOfInstallments.
        /// </summary>
        [JsonProperty("NumberOfInstallments")]
        public int NumberOfInstallments { get; set; }

        /// <summary>
        /// Gets or sets FirstInstallmentAmount.
        /// </summary>
        [JsonProperty("FirstInstallmentAmount")]
        public double FirstInstallmentAmount { get; set; }

        /// <summary>
        /// Gets or sets InstallmentAmount.
        /// </summary>
        [JsonProperty("InstallmentAmount")]
        public double InstallmentAmount { get; set; }

        /// <summary>
        /// Gets or sets LastInstallmentAmount.
        /// </summary>
        [JsonProperty("LastInstallmentAmount")]
        public double LastInstallmentAmount { get; set; }

        /// <summary>
        /// Gets or sets Links.
        /// </summary>
        [JsonProperty("Links", NullValueHandling = NullValueHandling.Ignore)]
        public Models.LinksModel Links { get; set; }

        /// <summary>
        /// Gets or sets TermsAndConditionsBrief.
        /// </summary>
        [JsonProperty("TermsAndConditionsBrief", NullValueHandling = NullValueHandling.Ignore)]
        public string TermsAndConditionsBrief { get; set; }

        /// <summary>
        /// Gets or sets InstallmentFrequency.
        /// </summary>
        [JsonProperty("InstallmentFrequency", NullValueHandling = NullValueHandling.Ignore)]
        public string InstallmentFrequency { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"PaymentPlanOptionModel : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is PaymentPlanOptionModel other &&
                (this.NumberOfInstallments.Equals(other.NumberOfInstallments)) &&
                (this.FirstInstallmentAmount.Equals(other.FirstInstallmentAmount)) &&
                (this.InstallmentAmount.Equals(other.InstallmentAmount)) &&
                (this.LastInstallmentAmount.Equals(other.LastInstallmentAmount)) &&
                (this.Links == null && other.Links == null ||
                 this.Links?.Equals(other.Links) == true) &&
                (this.TermsAndConditionsBrief == null && other.TermsAndConditionsBrief == null ||
                 this.TermsAndConditionsBrief?.Equals(other.TermsAndConditionsBrief) == true) &&
                (this.InstallmentFrequency == null && other.InstallmentFrequency == null ||
                 this.InstallmentFrequency?.Equals(other.InstallmentFrequency) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"NumberOfInstallments = {this.NumberOfInstallments}");
            toStringOutput.Add($"FirstInstallmentAmount = {this.FirstInstallmentAmount}");
            toStringOutput.Add($"InstallmentAmount = {this.InstallmentAmount}");
            toStringOutput.Add($"LastInstallmentAmount = {this.LastInstallmentAmount}");
            toStringOutput.Add($"Links = {(this.Links == null ? "null" : this.Links.ToString())}");
            toStringOutput.Add($"TermsAndConditionsBrief = {this.TermsAndConditionsBrief ?? "null"}");
            toStringOutput.Add($"InstallmentFrequency = {this.InstallmentFrequency ?? "null"}");
        }
    }
}