// <copyright file="PaymentInfo.cs" company="APIMatic">
// SplititWebApiV3.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SplititWebApiV3.Standard;
using SplititWebApiV3.Standard.Utilities;

namespace SplititWebApiV3.Standard.Models
{
    /// <summary>
    /// PaymentInfo.
    /// </summary>
    public class PaymentInfo
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PaymentInfo"/> class.
        /// </summary>
        public PaymentInfo()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PaymentInfo"/> class.
        /// </summary>
        /// <param name="cardBin">CardBin.</param>
        /// <param name="cardType">CardType.</param>
        public PaymentInfo(
            string cardBin = "",
            Models.CardTypeEnum? cardType = null)
        {
            this.CardBin = cardBin;
            this.CardType = cardType;
        }

        /// <summary>
        /// Gets or sets CardBin.
        /// </summary>
        [JsonProperty("CardBin", NullValueHandling = NullValueHandling.Ignore)]
        public string CardBin { get; set; }

        /// <summary>
        /// Gets or sets CardType.
        /// </summary>
        [JsonProperty("CardType", NullValueHandling = NullValueHandling.Ignore)]
        public Models.CardTypeEnum? CardType { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"PaymentInfo : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is PaymentInfo other &&
                (this.CardBin == null && other.CardBin == null ||
                 this.CardBin?.Equals(other.CardBin) == true) &&
                (this.CardType == null && other.CardType == null ||
                 this.CardType?.Equals(other.CardType) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"CardBin = {this.CardBin ?? "null"}");
            toStringOutput.Add($"CardType = {(this.CardType == null ? "null" : this.CardType.ToString())}");
        }
    }
}