// <copyright file="PlanStatusEnum.cs" company="APIMatic">
// SplititWebApiV3.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using SplititWebApiV3.Standard;
using SplititWebApiV3.Standard.Utilities;

namespace SplititWebApiV3.Standard.Models
{
    /// <summary>
    /// PlanStatusEnum.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum PlanStatusEnum
    {
        /// <summary>
        /// Initialized.
        /// </summary>
        [EnumMember(Value = "Initialized")]
        Initialized,

        /// <summary>
        /// PendingCapture.
        /// </summary>
        [EnumMember(Value = "PendingCapture")]
        PendingCapture,

        /// <summary>
        /// Active.
        /// </summary>
        [EnumMember(Value = "Active")]
        Active,

        /// <summary>
        /// Cleared.
        /// </summary>
        [EnumMember(Value = "Cleared")]
        Cleared,

        /// <summary>
        /// Canceled.
        /// </summary>
        [EnumMember(Value = "Canceled")]
        Canceled
    }
}