// <copyright file="PlanDataModel.cs" company="APIMatic">
// SplititWebApiV3.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SplititWebApiV3.Standard;
using SplititWebApiV3.Standard.Utilities;

namespace SplititWebApiV3.Standard.Models
{
    /// <summary>
    /// PlanDataModel.
    /// </summary>
    public class PlanDataModel
    {
        private int? numberOfInstallments;
        private Dictionary<string, bool> shouldSerialize = new Dictionary<string, bool>
        {
            { "NumberOfInstallments", false },
        };

        /// <summary>
        /// Initializes a new instance of the <see cref="PlanDataModel"/> class.
        /// </summary>
        public PlanDataModel()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PlanDataModel"/> class.
        /// </summary>
        /// <param name="totalAmount">TotalAmount.</param>
        /// <param name="purchaseMethod">PurchaseMethod.</param>
        /// <param name="currency">Currency.</param>
        /// <param name="numberOfInstallments">NumberOfInstallments.</param>
        /// <param name="terminalId">TerminalId.</param>
        /// <param name="refOrderNumber">RefOrderNumber.</param>
        /// <param name="extendedParams">ExtendedParams.</param>
        /// <param name="firstInstallmentAmount">FirstInstallmentAmount.</param>
        /// <param name="firstInstallmentDate">FirstInstallmentDate.</param>
        public PlanDataModel(
            string totalAmount,
            Models.PurchaseMethodEnum purchaseMethod,
            string currency = "",
            int? numberOfInstallments = null,
            string terminalId = "",
            string refOrderNumber = "",
            Dictionary<string, string> extendedParams = null,
            string firstInstallmentAmount = "",
            DateTime? firstInstallmentDate = null)
        {
            this.TotalAmount = totalAmount;
            this.Currency = currency;

            if (numberOfInstallments != null)
            {
                this.NumberOfInstallments = numberOfInstallments;
            }
            this.TerminalId = terminalId;
            this.PurchaseMethod = purchaseMethod;
            this.RefOrderNumber = refOrderNumber;
            this.ExtendedParams = extendedParams;
            this.FirstInstallmentAmount = firstInstallmentAmount;
            this.FirstInstallmentDate = firstInstallmentDate;
        }

        /// <summary>
        /// Gets or sets TotalAmount.
        /// </summary>
        [JsonProperty("TotalAmount")]
        public string TotalAmount { get; set; }

        /// <summary>
        /// Gets or sets Currency.
        /// </summary>
        [JsonProperty("Currency", NullValueHandling = NullValueHandling.Ignore)]
        public string Currency { get; set; }

        /// <summary>
        /// Gets or sets NumberOfInstallments.
        /// </summary>
        [JsonProperty("NumberOfInstallments")]
        public int? NumberOfInstallments
        {
            get
            {
                return this.numberOfInstallments;
            }

            set
            {
                this.shouldSerialize["NumberOfInstallments"] = true;
                this.numberOfInstallments = value;
            }
        }

        /// <summary>
        /// Gets or sets TerminalId.
        /// </summary>
        [JsonProperty("TerminalId", NullValueHandling = NullValueHandling.Ignore)]
        public string TerminalId { get; set; }

        /// <summary>
        /// Gets or sets PurchaseMethod.
        /// </summary>
        [JsonProperty("PurchaseMethod")]
        public Models.PurchaseMethodEnum PurchaseMethod { get; set; }

        /// <summary>
        /// Gets or sets RefOrderNumber.
        /// </summary>
        [JsonProperty("RefOrderNumber", NullValueHandling = NullValueHandling.Ignore)]
        public string RefOrderNumber { get; set; }

        /// <summary>
        /// Gets or sets ExtendedParams.
        /// </summary>
        [JsonProperty("ExtendedParams", NullValueHandling = NullValueHandling.Ignore)]
        public Dictionary<string, string> ExtendedParams { get; set; }

        /// <summary>
        /// Gets or sets FirstInstallmentAmount.
        /// </summary>
        [JsonProperty("FirstInstallmentAmount", NullValueHandling = NullValueHandling.Ignore)]
        public string FirstInstallmentAmount { get; set; }

        /// <summary>
        /// Gets or sets FirstInstallmentDate.
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("FirstInstallmentDate", NullValueHandling = NullValueHandling.Ignore)]
        public DateTime? FirstInstallmentDate { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"PlanDataModel : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetNumberOfInstallments()
        {
            this.shouldSerialize["NumberOfInstallments"] = false;
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeNumberOfInstallments()
        {
            return this.shouldSerialize["NumberOfInstallments"];
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is PlanDataModel other &&
                (this.TotalAmount == null && other.TotalAmount == null ||
                 this.TotalAmount?.Equals(other.TotalAmount) == true) &&
                (this.Currency == null && other.Currency == null ||
                 this.Currency?.Equals(other.Currency) == true) &&
                (this.NumberOfInstallments == null && other.NumberOfInstallments == null ||
                 this.NumberOfInstallments?.Equals(other.NumberOfInstallments) == true) &&
                (this.TerminalId == null && other.TerminalId == null ||
                 this.TerminalId?.Equals(other.TerminalId) == true) &&
                (this.PurchaseMethod.Equals(other.PurchaseMethod)) &&
                (this.RefOrderNumber == null && other.RefOrderNumber == null ||
                 this.RefOrderNumber?.Equals(other.RefOrderNumber) == true) &&
                (this.ExtendedParams == null && other.ExtendedParams == null ||
                 this.ExtendedParams?.Equals(other.ExtendedParams) == true) &&
                (this.FirstInstallmentAmount == null && other.FirstInstallmentAmount == null ||
                 this.FirstInstallmentAmount?.Equals(other.FirstInstallmentAmount) == true) &&
                (this.FirstInstallmentDate == null && other.FirstInstallmentDate == null ||
                 this.FirstInstallmentDate?.Equals(other.FirstInstallmentDate) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"TotalAmount = {this.TotalAmount ?? "null"}");
            toStringOutput.Add($"Currency = {this.Currency ?? "null"}");
            toStringOutput.Add($"NumberOfInstallments = {(this.NumberOfInstallments == null ? "null" : this.NumberOfInstallments.ToString())}");
            toStringOutput.Add($"TerminalId = {this.TerminalId ?? "null"}");
            toStringOutput.Add($"PurchaseMethod = {this.PurchaseMethod}");
            toStringOutput.Add($"RefOrderNumber = {this.RefOrderNumber ?? "null"}");
            toStringOutput.Add($"ExtendedParams = {(this.ExtendedParams == null ? "null" : this.ExtendedParams.ToString())}");
            toStringOutput.Add($"FirstInstallmentAmount = {this.FirstInstallmentAmount ?? "null"}");
            toStringOutput.Add($"FirstInstallmentDate = {(this.FirstInstallmentDate == null ? "null" : this.FirstInstallmentDate.ToString())}");
        }
    }
}