// <copyright file="PlanData.cs" company="APIMatic">
// SplititWebApiV3.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SplititWebApiV3.Standard;
using SplititWebApiV3.Standard.Utilities;

namespace SplititWebApiV3.Standard.Models
{
    /// <summary>
    /// PlanData.
    /// </summary>
    public class PlanData
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PlanData"/> class.
        /// </summary>
        public PlanData()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PlanData"/> class.
        /// </summary>
        /// <param name="totalAmount">TotalAmount.</param>
        /// <param name="numberOfInstallments">NumberOfInstallments.</param>
        /// <param name="purchaseMethod">PurchaseMethod.</param>
        /// <param name="terminalId">TerminalId.</param>
        /// <param name="firstInstallmentAmount">FirstInstallmentAmount.</param>
        /// <param name="currency">Currency.</param>
        /// <param name="refOrderNumber">RefOrderNumber.</param>
        /// <param name="allowedInstallmentOptions">AllowedInstallmentOptions.</param>
        /// <param name="tags">Tags.</param>
        /// <param name="processingData">ProcessingData.</param>
        /// <param name="firstInstallmentDate">FirstInstallmentDate.</param>
        public PlanData(
            string totalAmount,
            int numberOfInstallments,
            Models.PurchaseMethodEnum purchaseMethod,
            string terminalId = "",
            double? firstInstallmentAmount = null,
            string currency = "",
            string refOrderNumber = "",
            List<int> allowedInstallmentOptions = null,
            Dictionary<string, string> tags = null,
            Models.ProcessingData processingData = null,
            DateTime? firstInstallmentDate = null)
        {
            this.TerminalId = terminalId;
            this.TotalAmount = totalAmount;
            this.FirstInstallmentAmount = firstInstallmentAmount;
            this.Currency = currency;
            this.NumberOfInstallments = numberOfInstallments;
            this.PurchaseMethod = purchaseMethod;
            this.RefOrderNumber = refOrderNumber;
            this.AllowedInstallmentOptions = allowedInstallmentOptions;
            this.Tags = tags;
            this.ProcessingData = processingData;
            this.FirstInstallmentDate = firstInstallmentDate;
        }

        /// <summary>
        /// Gets or sets TerminalId.
        /// </summary>
        [JsonProperty("TerminalId", NullValueHandling = NullValueHandling.Ignore)]
        public string TerminalId { get; set; }

        /// <summary>
        /// Gets or sets TotalAmount.
        /// </summary>
        [JsonProperty("TotalAmount")]
        public string TotalAmount { get; set; }

        /// <summary>
        /// Gets or sets FirstInstallmentAmount.
        /// </summary>
        [JsonProperty("FirstInstallmentAmount", NullValueHandling = NullValueHandling.Ignore)]
        public double? FirstInstallmentAmount { get; set; }

        /// <summary>
        /// Gets or sets Currency.
        /// </summary>
        [JsonProperty("Currency", NullValueHandling = NullValueHandling.Ignore)]
        public string Currency { get; set; }

        /// <summary>
        /// Gets or sets NumberOfInstallments.
        /// </summary>
        [JsonProperty("NumberOfInstallments")]
        public int NumberOfInstallments { get; set; }

        /// <summary>
        /// Gets or sets PurchaseMethod.
        /// </summary>
        [JsonProperty("PurchaseMethod")]
        public Models.PurchaseMethodEnum PurchaseMethod { get; set; }

        /// <summary>
        /// Gets or sets RefOrderNumber.
        /// </summary>
        [JsonProperty("RefOrderNumber", NullValueHandling = NullValueHandling.Ignore)]
        public string RefOrderNumber { get; set; }

        /// <summary>
        /// Gets or sets AllowedInstallmentOptions.
        /// </summary>
        [JsonProperty("AllowedInstallmentOptions", NullValueHandling = NullValueHandling.Ignore)]
        public List<int> AllowedInstallmentOptions { get; set; }

        /// <summary>
        /// Gets or sets Tags.
        /// </summary>
        [JsonProperty("Tags", NullValueHandling = NullValueHandling.Ignore)]
        public Dictionary<string, string> Tags { get; set; }

        /// <summary>
        /// Gets or sets ProcessingData.
        /// </summary>
        [JsonProperty("ProcessingData", NullValueHandling = NullValueHandling.Ignore)]
        public Models.ProcessingData ProcessingData { get; set; }

        /// <summary>
        /// Gets or sets FirstInstallmentDate.
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("FirstInstallmentDate", NullValueHandling = NullValueHandling.Ignore)]
        public DateTime? FirstInstallmentDate { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"PlanData : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is PlanData other &&
                (this.TerminalId == null && other.TerminalId == null ||
                 this.TerminalId?.Equals(other.TerminalId) == true) &&
                (this.TotalAmount == null && other.TotalAmount == null ||
                 this.TotalAmount?.Equals(other.TotalAmount) == true) &&
                (this.FirstInstallmentAmount == null && other.FirstInstallmentAmount == null ||
                 this.FirstInstallmentAmount?.Equals(other.FirstInstallmentAmount) == true) &&
                (this.Currency == null && other.Currency == null ||
                 this.Currency?.Equals(other.Currency) == true) &&
                (this.NumberOfInstallments.Equals(other.NumberOfInstallments)) &&
                (this.PurchaseMethod.Equals(other.PurchaseMethod)) &&
                (this.RefOrderNumber == null && other.RefOrderNumber == null ||
                 this.RefOrderNumber?.Equals(other.RefOrderNumber) == true) &&
                (this.AllowedInstallmentOptions == null && other.AllowedInstallmentOptions == null ||
                 this.AllowedInstallmentOptions?.Equals(other.AllowedInstallmentOptions) == true) &&
                (this.Tags == null && other.Tags == null ||
                 this.Tags?.Equals(other.Tags) == true) &&
                (this.ProcessingData == null && other.ProcessingData == null ||
                 this.ProcessingData?.Equals(other.ProcessingData) == true) &&
                (this.FirstInstallmentDate == null && other.FirstInstallmentDate == null ||
                 this.FirstInstallmentDate?.Equals(other.FirstInstallmentDate) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"TerminalId = {this.TerminalId ?? "null"}");
            toStringOutput.Add($"TotalAmount = {this.TotalAmount ?? "null"}");
            toStringOutput.Add($"FirstInstallmentAmount = {(this.FirstInstallmentAmount == null ? "null" : this.FirstInstallmentAmount.ToString())}");
            toStringOutput.Add($"Currency = {this.Currency ?? "null"}");
            toStringOutput.Add($"NumberOfInstallments = {this.NumberOfInstallments}");
            toStringOutput.Add($"PurchaseMethod = {this.PurchaseMethod}");
            toStringOutput.Add($"RefOrderNumber = {this.RefOrderNumber ?? "null"}");
            toStringOutput.Add($"AllowedInstallmentOptions = {(this.AllowedInstallmentOptions == null ? "null" : $"[{string.Join(", ", this.AllowedInstallmentOptions)} ]")}");
            toStringOutput.Add($"Tags = {(this.Tags == null ? "null" : this.Tags.ToString())}");
            toStringOutput.Add($"ProcessingData = {(this.ProcessingData == null ? "null" : this.ProcessingData.ToString())}");
            toStringOutput.Add($"FirstInstallmentDate = {(this.FirstInstallmentDate == null ? "null" : this.FirstInstallmentDate.ToString())}");
        }
    }
}