// <copyright file="ProcessingData.cs" company="APIMatic">
// SplititWebApiV3.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SplititWebApiV3.Standard;
using SplititWebApiV3.Standard.Utilities;

namespace SplititWebApiV3.Standard.Models
{
    /// <summary>
    /// ProcessingData.
    /// </summary>
    public class ProcessingData
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ProcessingData"/> class.
        /// </summary>
        public ProcessingData()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ProcessingData"/> class.
        /// </summary>
        /// <param name="attemptThreeDSecured">AttemptThreeDSecured.</param>
        /// <param name="softDescriptor">SoftDescriptor.</param>
        /// <param name="threeDSData">ThreeDSData.</param>
        public ProcessingData(
            bool? attemptThreeDSecured = false,
            string softDescriptor = "",
            Models.ThreeDSData threeDSData = null)
        {
            this.AttemptThreeDSecured = attemptThreeDSecured;
            this.SoftDescriptor = softDescriptor;
            this.ThreeDSData = threeDSData;
        }

        /// <summary>
        /// Gets or sets AttemptThreeDSecured.
        /// </summary>
        [JsonProperty("AttemptThreeDSecured", NullValueHandling = NullValueHandling.Ignore)]
        public bool? AttemptThreeDSecured { get; set; }

        /// <summary>
        /// Gets or sets SoftDescriptor.
        /// </summary>
        [JsonProperty("SoftDescriptor", NullValueHandling = NullValueHandling.Ignore)]
        public string SoftDescriptor { get; set; }

        /// <summary>
        /// Gets or sets ThreeDSData.
        /// </summary>
        [JsonProperty("ThreeDSData", NullValueHandling = NullValueHandling.Ignore)]
        public Models.ThreeDSData ThreeDSData { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"ProcessingData : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is ProcessingData other &&
                (this.AttemptThreeDSecured == null && other.AttemptThreeDSecured == null ||
                 this.AttemptThreeDSecured?.Equals(other.AttemptThreeDSecured) == true) &&
                (this.SoftDescriptor == null && other.SoftDescriptor == null ||
                 this.SoftDescriptor?.Equals(other.SoftDescriptor) == true) &&
                (this.ThreeDSData == null && other.ThreeDSData == null ||
                 this.ThreeDSData?.Equals(other.ThreeDSData) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"AttemptThreeDSecured = {(this.AttemptThreeDSecured == null ? "null" : this.AttemptThreeDSecured.ToString())}");
            toStringOutput.Add($"SoftDescriptor = {this.SoftDescriptor ?? "null"}");
            toStringOutput.Add($"ThreeDSData = {(this.ThreeDSData == null ? "null" : this.ThreeDSData.ToString())}");
        }
    }
}