// <copyright file="PurchaseMethodEnum.cs" company="APIMatic">
// SplititWebApiV3.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using SplititWebApiV3.Standard;
using SplititWebApiV3.Standard.Utilities;

namespace SplititWebApiV3.Standard.Models
{
    /// <summary>
    /// PurchaseMethodEnum.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum PurchaseMethodEnum
    {
        /// <summary>
        /// InStore.
        /// </summary>
        [EnumMember(Value = "InStore")]
        InStore,

        /// <summary>
        /// PhoneOrder.
        /// </summary>
        [EnumMember(Value = "PhoneOrder")]
        PhoneOrder,

        /// <summary>
        /// ECommerce.
        /// </summary>
        [EnumMember(Value = "ECommerce")]
        ECommerce
    }
}