// <copyright file="RedirectionEndpointsModel.cs" company="APIMatic">
// SplititWebApiV3.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SplititWebApiV3.Standard;
using SplititWebApiV3.Standard.Utilities;

namespace SplititWebApiV3.Standard.Models
{
    /// <summary>
    /// RedirectionEndpointsModel.
    /// </summary>
    public class RedirectionEndpointsModel
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RedirectionEndpointsModel"/> class.
        /// </summary>
        public RedirectionEndpointsModel()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="RedirectionEndpointsModel"/> class.
        /// </summary>
        /// <param name="authorizeSucceeded">AuthorizeSucceeded.</param>
        /// <param name="succeeded">Succeeded.</param>
        /// <param name="authorizeFailed">AuthorizeFailed.</param>
        /// <param name="failed">Failed.</param>
        public RedirectionEndpointsModel(
            string authorizeSucceeded = "",
            string succeeded = "",
            string authorizeFailed = "",
            string failed = "")
        {
            this.AuthorizeSucceeded = authorizeSucceeded;
            this.Succeeded = succeeded;
            this.AuthorizeFailed = authorizeFailed;
            this.Failed = failed;
        }

        /// <summary>
        /// Gets or sets AuthorizeSucceeded.
        /// </summary>
        [JsonProperty("AuthorizeSucceeded", NullValueHandling = NullValueHandling.Ignore)]
        public string AuthorizeSucceeded { get; set; }

        /// <summary>
        /// Gets or sets Succeeded.
        /// </summary>
        [JsonProperty("Succeeded", NullValueHandling = NullValueHandling.Ignore)]
        public string Succeeded { get; set; }

        /// <summary>
        /// Gets or sets AuthorizeFailed.
        /// </summary>
        [JsonProperty("AuthorizeFailed", NullValueHandling = NullValueHandling.Ignore)]
        public string AuthorizeFailed { get; set; }

        /// <summary>
        /// Gets or sets Failed.
        /// </summary>
        [JsonProperty("Failed", NullValueHandling = NullValueHandling.Ignore)]
        public string Failed { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"RedirectionEndpointsModel : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is RedirectionEndpointsModel other &&
                (this.AuthorizeSucceeded == null && other.AuthorizeSucceeded == null ||
                 this.AuthorizeSucceeded?.Equals(other.AuthorizeSucceeded) == true) &&
                (this.Succeeded == null && other.Succeeded == null ||
                 this.Succeeded?.Equals(other.Succeeded) == true) &&
                (this.AuthorizeFailed == null && other.AuthorizeFailed == null ||
                 this.AuthorizeFailed?.Equals(other.AuthorizeFailed) == true) &&
                (this.Failed == null && other.Failed == null ||
                 this.Failed?.Equals(other.Failed) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"AuthorizeSucceeded = {this.AuthorizeSucceeded ?? "null"}");
            toStringOutput.Add($"Succeeded = {this.Succeeded ?? "null"}");
            toStringOutput.Add($"AuthorizeFailed = {this.AuthorizeFailed ?? "null"}");
            toStringOutput.Add($"Failed = {this.Failed ?? "null"}");
        }
    }
}