// <copyright file="RefundSummary.cs" company="APIMatic">
// SplititWebApiV3.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SplititWebApiV3.Standard;
using SplititWebApiV3.Standard.Utilities;

namespace SplititWebApiV3.Standard.Models
{
    /// <summary>
    /// RefundSummary.
    /// </summary>
    public class RefundSummary
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RefundSummary"/> class.
        /// </summary>
        public RefundSummary()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="RefundSummary"/> class.
        /// </summary>
        /// <param name="totalAmount">TotalAmount.</param>
        /// <param name="failedAmount">FailedAmount.</param>
        /// <param name="succeededAmount">SucceededAmount.</param>
        /// <param name="pendingAmount">PendingAmount.</param>
        public RefundSummary(
            double? totalAmount = null,
            double? failedAmount = null,
            double? succeededAmount = null,
            double? pendingAmount = null)
        {
            this.TotalAmount = totalAmount;
            this.FailedAmount = failedAmount;
            this.SucceededAmount = succeededAmount;
            this.PendingAmount = pendingAmount;
        }

        /// <summary>
        /// Gets or sets TotalAmount.
        /// </summary>
        [JsonProperty("TotalAmount", NullValueHandling = NullValueHandling.Ignore)]
        public double? TotalAmount { get; set; }

        /// <summary>
        /// Gets or sets FailedAmount.
        /// </summary>
        [JsonProperty("FailedAmount", NullValueHandling = NullValueHandling.Ignore)]
        public double? FailedAmount { get; set; }

        /// <summary>
        /// Gets or sets SucceededAmount.
        /// </summary>
        [JsonProperty("SucceededAmount", NullValueHandling = NullValueHandling.Ignore)]
        public double? SucceededAmount { get; set; }

        /// <summary>
        /// Gets or sets PendingAmount.
        /// </summary>
        [JsonProperty("PendingAmount", NullValueHandling = NullValueHandling.Ignore)]
        public double? PendingAmount { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"RefundSummary : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is RefundSummary other &&
                (this.TotalAmount == null && other.TotalAmount == null ||
                 this.TotalAmount?.Equals(other.TotalAmount) == true) &&
                (this.FailedAmount == null && other.FailedAmount == null ||
                 this.FailedAmount?.Equals(other.FailedAmount) == true) &&
                (this.SucceededAmount == null && other.SucceededAmount == null ||
                 this.SucceededAmount?.Equals(other.SucceededAmount) == true) &&
                (this.PendingAmount == null && other.PendingAmount == null ||
                 this.PendingAmount?.Equals(other.PendingAmount) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"TotalAmount = {(this.TotalAmount == null ? "null" : this.TotalAmount.ToString())}");
            toStringOutput.Add($"FailedAmount = {(this.FailedAmount == null ? "null" : this.FailedAmount.ToString())}");
            toStringOutput.Add($"SucceededAmount = {(this.SucceededAmount == null ? "null" : this.SucceededAmount.ToString())}");
            toStringOutput.Add($"PendingAmount = {(this.PendingAmount == null ? "null" : this.PendingAmount.ToString())}");
        }
    }
}