// <copyright file="RefundModel.cs" company="APIMatic">
// SplititWebApiV3.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SplititWebApiV3.Standard;
using SplititWebApiV3.Standard.Utilities;

namespace SplititWebApiV3.Standard.Models
{
    /// <summary>
    /// RefundModel.
    /// </summary>
    public class RefundModel
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RefundModel"/> class.
        /// </summary>
        public RefundModel()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="RefundModel"/> class.
        /// </summary>
        /// <param name="submitDate">SubmitDate.</param>
        /// <param name="totalAmount">TotalAmount.</param>
        /// <param name="status">Status.</param>
        /// <param name="nonCreditRefundAmount">NonCreditRefundAmount.</param>
        /// <param name="creditRefundAmount">CreditRefundAmount.</param>
        /// <param name="refundId">RefundId.</param>
        /// <param name="referenceId">ReferenceId.</param>
        public RefundModel(
            DateTime submitDate,
            double totalAmount,
            Models.RefundStatusEnum status,
            double nonCreditRefundAmount,
            double creditRefundAmount,
            string refundId = "",
            string referenceId = "")
        {
            this.RefundId = refundId;
            this.SubmitDate = submitDate;
            this.TotalAmount = totalAmount;
            this.Status = status;
            this.NonCreditRefundAmount = nonCreditRefundAmount;
            this.CreditRefundAmount = creditRefundAmount;
            this.ReferenceId = referenceId;
        }

        /// <summary>
        /// Gets or sets RefundId.
        /// </summary>
        [JsonProperty("RefundId", NullValueHandling = NullValueHandling.Ignore)]
        public string RefundId { get; set; }

        /// <summary>
        /// Gets or sets SubmitDate.
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("SubmitDate")]
        public DateTime SubmitDate { get; set; }

        /// <summary>
        /// Gets or sets TotalAmount.
        /// </summary>
        [JsonProperty("TotalAmount")]
        public double TotalAmount { get; set; }

        /// <summary>
        /// Gets or sets Status.
        /// </summary>
        [JsonProperty("Status")]
        public Models.RefundStatusEnum Status { get; set; }

        /// <summary>
        /// Gets or sets NonCreditRefundAmount.
        /// </summary>
        [JsonProperty("NonCreditRefundAmount")]
        public double NonCreditRefundAmount { get; set; }

        /// <summary>
        /// Gets or sets CreditRefundAmount.
        /// </summary>
        [JsonProperty("CreditRefundAmount")]
        public double CreditRefundAmount { get; set; }

        /// <summary>
        /// Gets or sets ReferenceId.
        /// </summary>
        [JsonProperty("ReferenceId", NullValueHandling = NullValueHandling.Ignore)]
        public string ReferenceId { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"RefundModel : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is RefundModel other &&
                (this.RefundId == null && other.RefundId == null ||
                 this.RefundId?.Equals(other.RefundId) == true) &&
                (this.SubmitDate.Equals(other.SubmitDate)) &&
                (this.TotalAmount.Equals(other.TotalAmount)) &&
                (this.Status.Equals(other.Status)) &&
                (this.NonCreditRefundAmount.Equals(other.NonCreditRefundAmount)) &&
                (this.CreditRefundAmount.Equals(other.CreditRefundAmount)) &&
                (this.ReferenceId == null && other.ReferenceId == null ||
                 this.ReferenceId?.Equals(other.ReferenceId) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"RefundId = {this.RefundId ?? "null"}");
            toStringOutput.Add($"SubmitDate = {this.SubmitDate}");
            toStringOutput.Add($"TotalAmount = {this.TotalAmount}");
            toStringOutput.Add($"Status = {this.Status}");
            toStringOutput.Add($"NonCreditRefundAmount = {this.NonCreditRefundAmount}");
            toStringOutput.Add($"CreditRefundAmount = {this.CreditRefundAmount}");
            toStringOutput.Add($"ReferenceId = {this.ReferenceId ?? "null"}");
        }
    }
}