// <copyright file="RefundStrategyEnum.cs" company="APIMatic">
// SplititWebApiV3.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using SplititWebApiV3.Standard;
using SplititWebApiV3.Standard.Utilities;

namespace SplititWebApiV3.Standard.Models
{
    /// <summary>
    /// RefundStrategyEnum.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum RefundStrategyEnum
    {
        /// <summary>
        /// FutureInstallmentsFirst.
        /// </summary>
        [EnumMember(Value = "FutureInstallmentsFirst")]
        FutureInstallmentsFirst,

        /// <summary>
        /// FutureInstallmentsLast.
        /// </summary>
        [EnumMember(Value = "FutureInstallmentsLast")]
        FutureInstallmentsLast,

        /// <summary>
        /// FutureInstallmentsNotAllowed.
        /// </summary>
        [EnumMember(Value = "FutureInstallmentsNotAllowed")]
        FutureInstallmentsNotAllowed,

        /// <summary>
        /// ReduceFromLastInstallment.
        /// </summary>
        [EnumMember(Value = "ReduceFromLastInstallment")]
        ReduceFromLastInstallment
    }
}