// <copyright file="SearchInstallmentPlanResponseItem.cs" company="APIMatic">
// SplititWebApiV3.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SplititWebApiV3.Standard;
using SplititWebApiV3.Standard.Utilities;

namespace SplititWebApiV3.Standard.Models
{
    /// <summary>
    /// SearchInstallmentPlanResponseItem.
    /// </summary>
    public class SearchInstallmentPlanResponseItem
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SearchInstallmentPlanResponseItem"/> class.
        /// </summary>
        public SearchInstallmentPlanResponseItem()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SearchInstallmentPlanResponseItem"/> class.
        /// </summary>
        /// <param name="dateCreated">DateCreated.</param>
        /// <param name="status">Status.</param>
        /// <param name="installmentPlanNumber">InstallmentPlanNumber.</param>
        /// <param name="refOrderNumber">RefOrderNumber.</param>
        /// <param name="purchaseMethod">PurchaseMethod.</param>
        /// <param name="currency">Currency.</param>
        /// <param name="originalAmount">OriginalAmount.</param>
        /// <param name="amount">Amount.</param>
        /// <param name="authorization">Authorization.</param>
        /// <param name="shopper">Shopper.</param>
        /// <param name="billingAddress">BillingAddress.</param>
        /// <param name="paymentMethod">PaymentMethod.</param>
        /// <param name="extendedParams">ExtendedParams.</param>
        /// <param name="installments">Installments.</param>
        /// <param name="refunds">Refunds.</param>
        /// <param name="links">Links.</param>
        public SearchInstallmentPlanResponseItem(
            DateTime dateCreated,
            Models.PlanStatusEnum status,
            string installmentPlanNumber = "",
            string refOrderNumber = "",
            Models.PurchaseMethodEnum? purchaseMethod = null,
            string currency = "",
            double? originalAmount = null,
            double? amount = null,
            Models.AuthorizationModel authorization = null,
            Models.ShopperData shopper = null,
            Models.AddressData billingAddress = null,
            Models.PaymentMethodModel paymentMethod = null,
            Dictionary<string, string> extendedParams = null,
            List<Models.Installment> installments = null,
            List<Models.RefundModel> refunds = null,
            Models.LinksData links = null)
        {
            this.InstallmentPlanNumber = installmentPlanNumber;
            this.DateCreated = dateCreated;
            this.RefOrderNumber = refOrderNumber;
            this.PurchaseMethod = purchaseMethod;
            this.Status = status;
            this.Currency = currency;
            this.OriginalAmount = originalAmount;
            this.Amount = amount;
            this.Authorization = authorization;
            this.Shopper = shopper;
            this.BillingAddress = billingAddress;
            this.PaymentMethod = paymentMethod;
            this.ExtendedParams = extendedParams;
            this.Installments = installments;
            this.Refunds = refunds;
            this.Links = links;
        }

        /// <summary>
        /// Gets or sets InstallmentPlanNumber.
        /// </summary>
        [JsonProperty("InstallmentPlanNumber", NullValueHandling = NullValueHandling.Ignore)]
        public string InstallmentPlanNumber { get; set; }

        /// <summary>
        /// Gets or sets DateCreated.
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("DateCreated")]
        public DateTime DateCreated { get; set; }

        /// <summary>
        /// Gets or sets RefOrderNumber.
        /// </summary>
        [JsonProperty("RefOrderNumber", NullValueHandling = NullValueHandling.Ignore)]
        public string RefOrderNumber { get; set; }

        /// <summary>
        /// Gets or sets PurchaseMethod.
        /// </summary>
        [JsonProperty("PurchaseMethod", NullValueHandling = NullValueHandling.Ignore)]
        public Models.PurchaseMethodEnum? PurchaseMethod { get; set; }

        /// <summary>
        /// Gets or sets Status.
        /// </summary>
        [JsonProperty("Status")]
        public Models.PlanStatusEnum Status { get; set; }

        /// <summary>
        /// Gets or sets Currency.
        /// </summary>
        [JsonProperty("Currency", NullValueHandling = NullValueHandling.Ignore)]
        public string Currency { get; set; }

        /// <summary>
        /// Gets or sets OriginalAmount.
        /// </summary>
        [JsonProperty("OriginalAmount", NullValueHandling = NullValueHandling.Ignore)]
        public double? OriginalAmount { get; set; }

        /// <summary>
        /// Gets or sets Amount.
        /// </summary>
        [JsonProperty("Amount", NullValueHandling = NullValueHandling.Ignore)]
        public double? Amount { get; set; }

        /// <summary>
        /// Gets or sets Authorization.
        /// </summary>
        [JsonProperty("Authorization", NullValueHandling = NullValueHandling.Ignore)]
        public Models.AuthorizationModel Authorization { get; set; }

        /// <summary>
        /// Gets or sets Shopper.
        /// </summary>
        [JsonProperty("Shopper", NullValueHandling = NullValueHandling.Ignore)]
        public Models.ShopperData Shopper { get; set; }

        /// <summary>
        /// Gets or sets BillingAddress.
        /// </summary>
        [JsonProperty("BillingAddress", NullValueHandling = NullValueHandling.Ignore)]
        public Models.AddressData BillingAddress { get; set; }

        /// <summary>
        /// Gets or sets PaymentMethod.
        /// </summary>
        [JsonProperty("PaymentMethod", NullValueHandling = NullValueHandling.Ignore)]
        public Models.PaymentMethodModel PaymentMethod { get; set; }

        /// <summary>
        /// Gets or sets ExtendedParams.
        /// </summary>
        [JsonProperty("ExtendedParams", NullValueHandling = NullValueHandling.Ignore)]
        public Dictionary<string, string> ExtendedParams { get; set; }

        /// <summary>
        /// Gets or sets Installments.
        /// </summary>
        [JsonProperty("Installments", NullValueHandling = NullValueHandling.Ignore)]
        public List<Models.Installment> Installments { get; set; }

        /// <summary>
        /// Gets or sets Refunds.
        /// </summary>
        [JsonProperty("Refunds", NullValueHandling = NullValueHandling.Ignore)]
        public List<Models.RefundModel> Refunds { get; set; }

        /// <summary>
        /// Gets or sets Links.
        /// </summary>
        [JsonProperty("Links", NullValueHandling = NullValueHandling.Ignore)]
        public Models.LinksData Links { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"SearchInstallmentPlanResponseItem : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is SearchInstallmentPlanResponseItem other &&
                (this.InstallmentPlanNumber == null && other.InstallmentPlanNumber == null ||
                 this.InstallmentPlanNumber?.Equals(other.InstallmentPlanNumber) == true) &&
                (this.DateCreated.Equals(other.DateCreated)) &&
                (this.RefOrderNumber == null && other.RefOrderNumber == null ||
                 this.RefOrderNumber?.Equals(other.RefOrderNumber) == true) &&
                (this.PurchaseMethod == null && other.PurchaseMethod == null ||
                 this.PurchaseMethod?.Equals(other.PurchaseMethod) == true) &&
                (this.Status.Equals(other.Status)) &&
                (this.Currency == null && other.Currency == null ||
                 this.Currency?.Equals(other.Currency) == true) &&
                (this.OriginalAmount == null && other.OriginalAmount == null ||
                 this.OriginalAmount?.Equals(other.OriginalAmount) == true) &&
                (this.Amount == null && other.Amount == null ||
                 this.Amount?.Equals(other.Amount) == true) &&
                (this.Authorization == null && other.Authorization == null ||
                 this.Authorization?.Equals(other.Authorization) == true) &&
                (this.Shopper == null && other.Shopper == null ||
                 this.Shopper?.Equals(other.Shopper) == true) &&
                (this.BillingAddress == null && other.BillingAddress == null ||
                 this.BillingAddress?.Equals(other.BillingAddress) == true) &&
                (this.PaymentMethod == null && other.PaymentMethod == null ||
                 this.PaymentMethod?.Equals(other.PaymentMethod) == true) &&
                (this.ExtendedParams == null && other.ExtendedParams == null ||
                 this.ExtendedParams?.Equals(other.ExtendedParams) == true) &&
                (this.Installments == null && other.Installments == null ||
                 this.Installments?.Equals(other.Installments) == true) &&
                (this.Refunds == null && other.Refunds == null ||
                 this.Refunds?.Equals(other.Refunds) == true) &&
                (this.Links == null && other.Links == null ||
                 this.Links?.Equals(other.Links) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"InstallmentPlanNumber = {this.InstallmentPlanNumber ?? "null"}");
            toStringOutput.Add($"DateCreated = {this.DateCreated}");
            toStringOutput.Add($"RefOrderNumber = {this.RefOrderNumber ?? "null"}");
            toStringOutput.Add($"PurchaseMethod = {(this.PurchaseMethod == null ? "null" : this.PurchaseMethod.ToString())}");
            toStringOutput.Add($"Status = {this.Status}");
            toStringOutput.Add($"Currency = {this.Currency ?? "null"}");
            toStringOutput.Add($"OriginalAmount = {(this.OriginalAmount == null ? "null" : this.OriginalAmount.ToString())}");
            toStringOutput.Add($"Amount = {(this.Amount == null ? "null" : this.Amount.ToString())}");
            toStringOutput.Add($"Authorization = {(this.Authorization == null ? "null" : this.Authorization.ToString())}");
            toStringOutput.Add($"Shopper = {(this.Shopper == null ? "null" : this.Shopper.ToString())}");
            toStringOutput.Add($"BillingAddress = {(this.BillingAddress == null ? "null" : this.BillingAddress.ToString())}");
            toStringOutput.Add($"PaymentMethod = {(this.PaymentMethod == null ? "null" : this.PaymentMethod.ToString())}");
            toStringOutput.Add($"ExtendedParams = {(this.ExtendedParams == null ? "null" : this.ExtendedParams.ToString())}");
            toStringOutput.Add($"Installments = {(this.Installments == null ? "null" : $"[{string.Join(", ", this.Installments)} ]")}");
            toStringOutput.Add($"Refunds = {(this.Refunds == null ? "null" : $"[{string.Join(", ", this.Refunds)} ]")}");
            toStringOutput.Add($"Links = {(this.Links == null ? "null" : this.Links.ToString())}");
        }
    }
}