// <copyright file="ShippingStatusEnum.cs" company="APIMatic">
// SplititWebApiV3.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using SplititWebApiV3.Standard;
using SplititWebApiV3.Standard.Utilities;

namespace SplititWebApiV3.Standard.Models
{
    /// <summary>
    /// ShippingStatusEnum.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum ShippingStatusEnum
    {
        /// <summary>
        /// Pending.
        /// </summary>
        [EnumMember(Value = "Pending")]
        Pending,

        /// <summary>
        /// Shipped.
        /// </summary>
        [EnumMember(Value = "Shipped")]
        Shipped,

        /// <summary>
        /// Delivered.
        /// </summary>
        [EnumMember(Value = "Delivered")]
        Delivered
    }
}