// <copyright file="ShopperData.cs" company="APIMatic">
// SplititWebApiV3.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SplititWebApiV3.Standard;
using SplititWebApiV3.Standard.Utilities;

namespace SplititWebApiV3.Standard.Models
{
    /// <summary>
    /// ShopperData.
    /// </summary>
    public class ShopperData
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ShopperData"/> class.
        /// </summary>
        public ShopperData()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ShopperData"/> class.
        /// </summary>
        /// <param name="fullName">FullName.</param>
        /// <param name="email">Email.</param>
        /// <param name="phoneNumber">PhoneNumber.</param>
        /// <param name="culture">Culture.</param>
        /// <param name="externalId">ExternalId.</param>
        public ShopperData(
            string fullName = "",
            string email = "",
            string phoneNumber = "",
            string culture = "",
            string externalId = "")
        {
            this.FullName = fullName;
            this.Email = email;
            this.PhoneNumber = phoneNumber;
            this.Culture = culture;
            this.ExternalId = externalId;
        }

        /// <summary>
        /// Gets or sets FullName.
        /// </summary>
        [JsonProperty("FullName", NullValueHandling = NullValueHandling.Ignore)]
        public string FullName { get; set; }

        /// <summary>
        /// Gets or sets Email.
        /// </summary>
        [JsonProperty("Email", NullValueHandling = NullValueHandling.Ignore)]
        public string Email { get; set; }

        /// <summary>
        /// Gets or sets PhoneNumber.
        /// </summary>
        [JsonProperty("PhoneNumber", NullValueHandling = NullValueHandling.Ignore)]
        public string PhoneNumber { get; set; }

        /// <summary>
        /// Gets or sets Culture.
        /// </summary>
        [JsonProperty("Culture", NullValueHandling = NullValueHandling.Ignore)]
        public string Culture { get; set; }

        /// <summary>
        /// Gets or sets ExternalId.
        /// </summary>
        [JsonProperty("ExternalId", NullValueHandling = NullValueHandling.Ignore)]
        public string ExternalId { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"ShopperData : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is ShopperData other &&
                (this.FullName == null && other.FullName == null ||
                 this.FullName?.Equals(other.FullName) == true) &&
                (this.Email == null && other.Email == null ||
                 this.Email?.Equals(other.Email) == true) &&
                (this.PhoneNumber == null && other.PhoneNumber == null ||
                 this.PhoneNumber?.Equals(other.PhoneNumber) == true) &&
                (this.Culture == null && other.Culture == null ||
                 this.Culture?.Equals(other.Culture) == true) &&
                (this.ExternalId == null && other.ExternalId == null ||
                 this.ExternalId?.Equals(other.ExternalId) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"FullName = {this.FullName ?? "null"}");
            toStringOutput.Add($"Email = {this.Email ?? "null"}");
            toStringOutput.Add($"PhoneNumber = {this.PhoneNumber ?? "null"}");
            toStringOutput.Add($"Culture = {this.Culture ?? "null"}");
            toStringOutput.Add($"ExternalId = {this.ExternalId ?? "null"}");
        }
    }
}