// <copyright file="TestModesEnum.cs" company="APIMatic">
// SplititWebApiV3.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using SplititWebApiV3.Standard;
using SplititWebApiV3.Standard.Utilities;

namespace SplititWebApiV3.Standard.Models
{
    /// <summary>
    /// TestModesEnum.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum TestModesEnum
    {
        /// <summary>
        /// None.
        /// </summary>
        [EnumMember(Value = "None")]
        None,

        /// <summary>
        /// Regular.
        /// </summary>
        [EnumMember(Value = "Regular")]
        Regular,

        /// <summary>
        /// Fast.
        /// </summary>
        [EnumMember(Value = "Fast")]
        Fast,

        /// <summary>
        /// Automation.
        /// </summary>
        [EnumMember(Value = "Automation")]
        Automation
    }
}