// <copyright file="ThreeDSData.cs" company="APIMatic">
// SplititWebApiV3.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SplititWebApiV3.Standard;
using SplititWebApiV3.Standard.Utilities;

namespace SplititWebApiV3.Standard.Models
{
    /// <summary>
    /// ThreeDSData.
    /// </summary>
    public class ThreeDSData
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ThreeDSData"/> class.
        /// </summary>
        public ThreeDSData()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ThreeDSData"/> class.
        /// </summary>
        /// <param name="eCI">ECI.</param>
        /// <param name="cAVV">CAVV.</param>
        /// <param name="xID">XID.</param>
        /// <param name="directoryServerTxnId">DirectoryServerTxnId.</param>
        /// <param name="threeDSVersion">ThreeDSVersion.</param>
        /// <param name="transactionId">TransactionId.</param>
        public ThreeDSData(
            string eCI = "",
            string cAVV = "",
            string xID = "",
            string directoryServerTxnId = "",
            string threeDSVersion = "",
            string transactionId = "")
        {
            this.ECI = eCI;
            this.CAVV = cAVV;
            this.XID = xID;
            this.DirectoryServerTxnId = directoryServerTxnId;
            this.ThreeDSVersion = threeDSVersion;
            this.TransactionId = transactionId;
        }

        /// <summary>
        /// Gets or sets ECI.
        /// </summary>
        [JsonProperty("ECI", NullValueHandling = NullValueHandling.Ignore)]
        public string ECI { get; set; }

        /// <summary>
        /// Gets or sets CAVV.
        /// </summary>
        [JsonProperty("CAVV", NullValueHandling = NullValueHandling.Ignore)]
        public string CAVV { get; set; }

        /// <summary>
        /// Gets or sets XID.
        /// </summary>
        [JsonProperty("XID", NullValueHandling = NullValueHandling.Ignore)]
        public string XID { get; set; }

        /// <summary>
        /// Gets or sets DirectoryServerTxnId.
        /// </summary>
        [JsonProperty("DirectoryServerTxnId", NullValueHandling = NullValueHandling.Ignore)]
        public string DirectoryServerTxnId { get; set; }

        /// <summary>
        /// Gets or sets ThreeDSVersion.
        /// </summary>
        [JsonProperty("ThreeDSVersion", NullValueHandling = NullValueHandling.Ignore)]
        public string ThreeDSVersion { get; set; }

        /// <summary>
        /// Gets or sets TransactionId.
        /// </summary>
        [JsonProperty("TransactionId", NullValueHandling = NullValueHandling.Ignore)]
        public string TransactionId { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"ThreeDSData : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is ThreeDSData other &&
                (this.ECI == null && other.ECI == null ||
                 this.ECI?.Equals(other.ECI) == true) &&
                (this.CAVV == null && other.CAVV == null ||
                 this.CAVV?.Equals(other.CAVV) == true) &&
                (this.XID == null && other.XID == null ||
                 this.XID?.Equals(other.XID) == true) &&
                (this.DirectoryServerTxnId == null && other.DirectoryServerTxnId == null ||
                 this.DirectoryServerTxnId?.Equals(other.DirectoryServerTxnId) == true) &&
                (this.ThreeDSVersion == null && other.ThreeDSVersion == null ||
                 this.ThreeDSVersion?.Equals(other.ThreeDSVersion) == true) &&
                (this.TransactionId == null && other.TransactionId == null ||
                 this.TransactionId?.Equals(other.TransactionId) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"ECI = {this.ECI ?? "null"}");
            toStringOutput.Add($"CAVV = {this.CAVV ?? "null"}");
            toStringOutput.Add($"XID = {this.XID ?? "null"}");
            toStringOutput.Add($"DirectoryServerTxnId = {this.DirectoryServerTxnId ?? "null"}");
            toStringOutput.Add($"ThreeDSVersion = {this.ThreeDSVersion ?? "null"}");
            toStringOutput.Add($"TransactionId = {this.TransactionId ?? "null"}");
        }
    }
}