// <copyright file="ThreeDsRedirectDataV3.cs" company="APIMatic">
// SplititWebApiV3.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SplititWebApiV3.Standard;
using SplititWebApiV3.Standard.Utilities;

namespace SplititWebApiV3.Standard.Models
{
    /// <summary>
    /// ThreeDsRedirectDataV3.
    /// </summary>
    public class ThreeDsRedirectDataV3
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ThreeDsRedirectDataV3"/> class.
        /// </summary>
        public ThreeDsRedirectDataV3()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ThreeDsRedirectDataV3"/> class.
        /// </summary>
        /// <param name="url">Url.</param>
        /// <param name="verb">Verb.</param>
        /// <param name="mParams">Params.</param>
        /// <param name="clientRedirectUrl">ClientRedirectUrl.</param>
        public ThreeDsRedirectDataV3(
            string url = "",
            string verb = "",
            Dictionary<string, string> mParams = null,
            string clientRedirectUrl = "")
        {
            this.Url = url;
            this.Verb = verb;
            this.MParams = mParams;
            this.ClientRedirectUrl = clientRedirectUrl;
        }

        /// <summary>
        /// Gets or sets Url.
        /// </summary>
        [JsonProperty("Url", NullValueHandling = NullValueHandling.Ignore)]
        public string Url { get; set; }

        /// <summary>
        /// Gets or sets Verb.
        /// </summary>
        [JsonProperty("Verb", NullValueHandling = NullValueHandling.Ignore)]
        public string Verb { get; set; }

        /// <summary>
        /// Gets or sets MParams.
        /// </summary>
        [JsonProperty("Params", NullValueHandling = NullValueHandling.Ignore)]
        public Dictionary<string, string> MParams { get; set; }

        /// <summary>
        /// Gets or sets ClientRedirectUrl.
        /// </summary>
        [JsonProperty("ClientRedirectUrl", NullValueHandling = NullValueHandling.Ignore)]
        public string ClientRedirectUrl { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"ThreeDsRedirectDataV3 : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is ThreeDsRedirectDataV3 other &&
                (this.Url == null && other.Url == null ||
                 this.Url?.Equals(other.Url) == true) &&
                (this.Verb == null && other.Verb == null ||
                 this.Verb?.Equals(other.Verb) == true) &&
                (this.MParams == null && other.MParams == null ||
                 this.MParams?.Equals(other.MParams) == true) &&
                (this.ClientRedirectUrl == null && other.ClientRedirectUrl == null ||
                 this.ClientRedirectUrl?.Equals(other.ClientRedirectUrl) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Url = {this.Url ?? "null"}");
            toStringOutput.Add($"Verb = {this.Verb ?? "null"}");
            toStringOutput.Add($"MParams = {(this.MParams == null ? "null" : this.MParams.ToString())}");
            toStringOutput.Add($"ClientRedirectUrl = {this.ClientRedirectUrl ?? "null"}");
        }
    }
}