// <copyright file="UxSettingsModel.cs" company="APIMatic">
// SplititWebApiV3.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SplititWebApiV3.Standard;
using SplititWebApiV3.Standard.Utilities;

namespace SplititWebApiV3.Standard.Models
{
    /// <summary>
    /// UxSettingsModel.
    /// </summary>
    public class UxSettingsModel
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UxSettingsModel"/> class.
        /// </summary>
        public UxSettingsModel()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="UxSettingsModel"/> class.
        /// </summary>
        /// <param name="displayedInstallmentOptions">DisplayedInstallmentOptions.</param>
        public UxSettingsModel(
            List<int> displayedInstallmentOptions = null)
        {
            this.DisplayedInstallmentOptions = displayedInstallmentOptions;
        }

        /// <summary>
        /// Gets or sets DisplayedInstallmentOptions.
        /// </summary>
        [JsonProperty("DisplayedInstallmentOptions", NullValueHandling = NullValueHandling.Ignore)]
        public List<int> DisplayedInstallmentOptions { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"UxSettingsModel : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is UxSettingsModel other &&
                (this.DisplayedInstallmentOptions == null && other.DisplayedInstallmentOptions == null ||
                 this.DisplayedInstallmentOptions?.Equals(other.DisplayedInstallmentOptions) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"DisplayedInstallmentOptions = {(this.DisplayedInstallmentOptions == null ? "null" : $"[{string.Join(", ", this.DisplayedInstallmentOptions)} ]")}");
        }
    }
}