// <copyright file="VerifyAuthorizationResponse.cs" company="APIMatic">
// SplititWebApiV3.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SplititWebApiV3.Standard;
using SplititWebApiV3.Standard.Utilities;

namespace SplititWebApiV3.Standard.Models
{
    /// <summary>
    /// VerifyAuthorizationResponse.
    /// </summary>
    public class VerifyAuthorizationResponse
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="VerifyAuthorizationResponse"/> class.
        /// </summary>
        public VerifyAuthorizationResponse()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="VerifyAuthorizationResponse"/> class.
        /// </summary>
        /// <param name="isAuthorized">IsAuthorized.</param>
        /// <param name="authorizationAmount">AuthorizationAmount.</param>
        /// <param name="authorization">Authorization.</param>
        public VerifyAuthorizationResponse(
            bool isAuthorized,
            double? authorizationAmount = null,
            Models.AuthorizationModel authorization = null)
        {
            this.IsAuthorized = isAuthorized;
            this.AuthorizationAmount = authorizationAmount;
            this.Authorization = authorization;
        }

        /// <summary>
        /// Gets or sets IsAuthorized.
        /// </summary>
        [JsonProperty("IsAuthorized")]
        public bool IsAuthorized { get; set; }

        /// <summary>
        /// Gets or sets AuthorizationAmount.
        /// </summary>
        [JsonProperty("AuthorizationAmount", NullValueHandling = NullValueHandling.Ignore)]
        public double? AuthorizationAmount { get; set; }

        /// <summary>
        /// Gets or sets Authorization.
        /// </summary>
        [JsonProperty("Authorization", NullValueHandling = NullValueHandling.Ignore)]
        public Models.AuthorizationModel Authorization { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"VerifyAuthorizationResponse : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is VerifyAuthorizationResponse other &&
                (this.IsAuthorized.Equals(other.IsAuthorized)) &&
                (this.AuthorizationAmount == null && other.AuthorizationAmount == null ||
                 this.AuthorizationAmount?.Equals(other.AuthorizationAmount) == true) &&
                (this.Authorization == null && other.Authorization == null ||
                 this.Authorization?.Equals(other.Authorization) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"IsAuthorized = {this.IsAuthorized}");
            toStringOutput.Add($"AuthorizationAmount = {(this.AuthorizationAmount == null ? "null" : this.AuthorizationAmount.ToString())}");
            toStringOutput.Add($"Authorization = {(this.Authorization == null ? "null" : this.Authorization.ToString())}");
        }
    }
}