// <copyright file="OAuthTokenExtensions.cs" company="APIMatic">
// SplititWebApiV3.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using System;
using SplititWebApiV3.Standard.Models;

namespace SplititWebApiV3.Standard.Authentication
{
    internal static class OAuthTokenExtensions
    {
        internal static bool IsTokenExpired(this OAuthToken token, TimeSpan? clockSkew)
        {
            if (token == null)
            {
                throw new InvalidOperationException("OAuth token is missing.");
            }

            if (token.Expiry == null) return true;
            return token.Expiry < DateTimeOffset.UtcNow.Subtract(clockSkew ?? TimeSpan.Zero).ToUnixTimeSeconds();    
        }
    }
}