// <copyright file="InstallmentPlanController.cs" company="APIMatic">
// SplititWebApiV3.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using System;
using System.Collections.Generic;
using System.Dynamic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using APIMatic.Core;
using APIMatic.Core.Types;
using APIMatic.Core.Utilities;
using APIMatic.Core.Utilities.Date.Xml;
using Newtonsoft.Json.Converters;
using SplititWebApiV3.Standard;
using SplititWebApiV3.Standard.Exceptions;
using SplititWebApiV3.Standard.Http.Client;
using SplititWebApiV3.Standard.Utilities;
using System.Net.Http;

namespace SplititWebApiV3.Standard.Controllers
{
    /// <summary>
    /// InstallmentPlanController.
    /// </summary>
    public class InstallmentPlanController : BaseController
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="InstallmentPlanController"/> class.
        /// </summary>
        internal InstallmentPlanController(GlobalConfiguration globalConfiguration) : base(globalConfiguration) { }

        /// <summary>
        /// InstallmentPlan_Get EndPoint.
        /// </summary>
        /// <param name="installmentPlanNumber">Required parameter: .</param>
        /// <param name="xSplititTouchPoint">Optional parameter: TouchPoint.</param>
        /// <returns>Returns the Models.InstallmentPlanGetResponse response from the API call.</returns>
        public Models.InstallmentPlanGetResponse InstallmentPlanGet(
                string installmentPlanNumber,
                string xSplititTouchPoint = null)
            => CoreHelper.RunTask(InstallmentPlanGetAsync(installmentPlanNumber, xSplititTouchPoint));

        /// <summary>
        /// InstallmentPlan_Get EndPoint.
        /// </summary>
        /// <param name="installmentPlanNumber">Required parameter: .</param>
        /// <param name="xSplititTouchPoint">Optional parameter: TouchPoint.</param>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the Models.InstallmentPlanGetResponse response from the API call.</returns>
        public async Task<Models.InstallmentPlanGetResponse> InstallmentPlanGetAsync(
                string installmentPlanNumber,
                string xSplititTouchPoint = null,
                CancellationToken cancellationToken = default)
            => await CreateApiCall<Models.InstallmentPlanGetResponse>()
              .RequestBuilder(_requestBuilder => _requestBuilder
                  .Setup(HttpMethod.Get, "/api/installmentplans/{installmentPlanNumber}")
                  .WithOrAuth(_orAuth => _orAuth
                      .Add("OAuth2-sandbox")
                      .Add("OAuth2-production")
                  )
                  .Parameters(_parameters => _parameters
                      .Template(_template => _template.Setup("installmentPlanNumber", installmentPlanNumber))
                      .Header(_header => _header.Setup("X-Splitit-TouchPoint", xSplititTouchPoint))))
              .ResponseHandler(_responseHandler => _responseHandler
                  .ErrorCase("401", CreateErrorCase("", (_reason, _context) => new FailedResponseException(_reason, _context)))
                  .ErrorCase("403", CreateErrorCase("", (_reason, _context) => new FailedResponseException(_reason, _context)))
                  .ErrorCase("404", CreateErrorCase("", (_reason, _context) => new FailedResponseException(_reason, _context)))
                  .ErrorCase("500", CreateErrorCase("", (_reason, _context) => new FailedResponseException(_reason, _context))))
              .ExecuteAsync(cancellationToken).ConfigureAwait(false);

        /// <summary>
        /// InstallmentPlan_Search EndPoint.
        /// </summary>
        /// <param name="installmentPlanNumber">Optional parameter: .</param>
        /// <param name="refOrderNumber">Optional parameter: .</param>
        /// <param name="extendedParams">Optional parameter: .</param>
        /// <param name="xSplititTouchPoint">Optional parameter: TouchPoint.</param>
        /// <returns>Returns the Models.InstallmentPlanSearchResponse response from the API call.</returns>
        public Models.InstallmentPlanSearchResponse InstallmentPlanSearch(
                string installmentPlanNumber = null,
                string refOrderNumber = null,
                object extendedParams = null,
                string xSplititTouchPoint = null)
            => CoreHelper.RunTask(InstallmentPlanSearchAsync(installmentPlanNumber, refOrderNumber, extendedParams, xSplititTouchPoint));

        /// <summary>
        /// InstallmentPlan_Search EndPoint.
        /// </summary>
        /// <param name="installmentPlanNumber">Optional parameter: .</param>
        /// <param name="refOrderNumber">Optional parameter: .</param>
        /// <param name="extendedParams">Optional parameter: .</param>
        /// <param name="xSplititTouchPoint">Optional parameter: TouchPoint.</param>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the Models.InstallmentPlanSearchResponse response from the API call.</returns>
        public async Task<Models.InstallmentPlanSearchResponse> InstallmentPlanSearchAsync(
                string installmentPlanNumber = null,
                string refOrderNumber = null,
                object extendedParams = null,
                string xSplititTouchPoint = null,
                CancellationToken cancellationToken = default)
            => await CreateApiCall<Models.InstallmentPlanSearchResponse>()
              .RequestBuilder(_requestBuilder => _requestBuilder
                  .Setup(HttpMethod.Get, "/api/installmentplans/search")
                  .WithOrAuth(_orAuth => _orAuth
                      .Add("OAuth2-sandbox")
                      .Add("OAuth2-production")
                  )
                  .Parameters(_parameters => _parameters
                      .Query(_query => _query.Setup("installmentPlanNumber", installmentPlanNumber))
                      .Query(_query => _query.Setup("refOrderNumber", refOrderNumber))
                      .Query(_query => _query.Setup("extendedParams", extendedParams))
                      .Header(_header => _header.Setup("X-Splitit-TouchPoint", xSplititTouchPoint))))
              .ResponseHandler(_responseHandler => _responseHandler
                  .ErrorCase("401", CreateErrorCase("", (_reason, _context) => new FailedResponseException(_reason, _context)))
                  .ErrorCase("403", CreateErrorCase("", (_reason, _context) => new FailedResponseException(_reason, _context)))
                  .ErrorCase("404", CreateErrorCase("", (_reason, _context) => new FailedResponseException(_reason, _context)))
                  .ErrorCase("500", CreateErrorCase("", (_reason, _context) => new FailedResponseException(_reason, _context))))
              .ExecuteAsync(cancellationToken).ConfigureAwait(false);

        /// <summary>
        /// InstallmentPlan_Post EndPoint.
        /// </summary>
        /// <param name="xSplititIdempotencyKey">Required parameter: .</param>
        /// <param name="body">Required parameter: .</param>
        /// <param name="xSplititTestMode">Optional parameter: Example: .</param>
        /// <param name="xSplititTouchPoint">Optional parameter: TouchPoint.</param>
        /// <returns>Returns the Models.InitiatePlanResponse response from the API call.</returns>
        public Models.InitiatePlanResponse InstallmentPlanPost(
                string xSplititIdempotencyKey,
                Models.InstallmentPlanInitiateRequest body,
                Models.TestModesEnum? xSplititTestMode = null,
                string xSplititTouchPoint = null)
            => CoreHelper.RunTask(InstallmentPlanPostAsync(xSplititIdempotencyKey, body, xSplititTestMode, xSplititTouchPoint));

        /// <summary>
        /// InstallmentPlan_Post EndPoint.
        /// </summary>
        /// <param name="xSplititIdempotencyKey">Required parameter: .</param>
        /// <param name="body">Required parameter: .</param>
        /// <param name="xSplititTestMode">Optional parameter: Example: .</param>
        /// <param name="xSplititTouchPoint">Optional parameter: TouchPoint.</param>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the Models.InitiatePlanResponse response from the API call.</returns>
        public async Task<Models.InitiatePlanResponse> InstallmentPlanPostAsync(
                string xSplititIdempotencyKey,
                Models.InstallmentPlanInitiateRequest body,
                Models.TestModesEnum? xSplititTestMode = null,
                string xSplititTouchPoint = null,
                CancellationToken cancellationToken = default)
            => await CreateApiCall<Models.InitiatePlanResponse>()
              .RequestBuilder(_requestBuilder => _requestBuilder
                  .Setup(HttpMethod.Post, "/api/installmentplans/initiate")
                  .WithOrAuth(_orAuth => _orAuth
                      .Add("OAuth2-sandbox")
                      .Add("OAuth2-production")
                  )
                  .Parameters(_parameters => _parameters
                      .Body(_bodyParameter => _bodyParameter.Setup(body))
                      .Header(_header => _header.Setup("X-Splitit-IdempotencyKey", xSplititIdempotencyKey))
                      .Header(_header => _header.Setup("Content-Type", "application/json-patch+json"))
                      .Header(_header => _header.Setup("X-Splitit-TestMode", (xSplititTestMode.HasValue) ? ApiHelper.JsonSerialize(xSplititTestMode.Value).Trim('\"') : null))
                      .Header(_header => _header.Setup("X-Splitit-TouchPoint", xSplititTouchPoint))))
              .ResponseHandler(_responseHandler => _responseHandler
                  .ErrorCase("400", CreateErrorCase("", (_reason, _context) => new PlanErrorResponseException(_reason, _context)))
                  .ErrorCase("401", CreateErrorCase("", (_reason, _context) => new FailedResponseException(_reason, _context)))
                  .ErrorCase("403", CreateErrorCase("", (_reason, _context) => new FailedResponseException(_reason, _context)))
                  .ErrorCase("404", CreateErrorCase("", (_reason, _context) => new FailedResponseException(_reason, _context)))
                  .ErrorCase("500", CreateErrorCase("", (_reason, _context) => new FailedResponseException(_reason, _context))))
              .ExecuteAsync(cancellationToken).ConfigureAwait(false);

        /// <summary>
        /// InstallmentPlan_Post2 EndPoint.
        /// </summary>
        /// <param name="xSplititIdempotencyKey">Required parameter: .</param>
        /// <param name="body">Required parameter: .</param>
        /// <param name="xSplititTestMode">Optional parameter: Example: .</param>
        /// <param name="xSplititTouchPoint">Optional parameter: TouchPoint.</param>
        /// <returns>Returns the Models.InstallmentPlanCreateResponse response from the API call.</returns>
        public Models.InstallmentPlanCreateResponse InstallmentPlanPost2(
                string xSplititIdempotencyKey,
                Models.InstallmentPlanCreateRequest body,
                Models.TestModesEnum? xSplititTestMode = null,
                string xSplititTouchPoint = null)
            => CoreHelper.RunTask(InstallmentPlanPost2Async(xSplititIdempotencyKey, body, xSplititTestMode, xSplititTouchPoint));

        /// <summary>
        /// InstallmentPlan_Post2 EndPoint.
        /// </summary>
        /// <param name="xSplititIdempotencyKey">Required parameter: .</param>
        /// <param name="body">Required parameter: .</param>
        /// <param name="xSplititTestMode">Optional parameter: Example: .</param>
        /// <param name="xSplititTouchPoint">Optional parameter: TouchPoint.</param>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the Models.InstallmentPlanCreateResponse response from the API call.</returns>
        public async Task<Models.InstallmentPlanCreateResponse> InstallmentPlanPost2Async(
                string xSplititIdempotencyKey,
                Models.InstallmentPlanCreateRequest body,
                Models.TestModesEnum? xSplititTestMode = null,
                string xSplititTouchPoint = null,
                CancellationToken cancellationToken = default)
            => await CreateApiCall<Models.InstallmentPlanCreateResponse>()
              .RequestBuilder(_requestBuilder => _requestBuilder
                  .Setup(HttpMethod.Post, "/api/installmentplans")
                  .WithOrAuth(_orAuth => _orAuth
                      .Add("OAuth2-sandbox")
                      .Add("OAuth2-production")
                  )
                  .Parameters(_parameters => _parameters
                      .Body(_bodyParameter => _bodyParameter.Setup(body))
                      .Header(_header => _header.Setup("X-Splitit-IdempotencyKey", xSplititIdempotencyKey))
                      .Header(_header => _header.Setup("Content-Type", "application/json-patch+json"))
                      .Header(_header => _header.Setup("X-Splitit-TestMode", (xSplititTestMode.HasValue) ? ApiHelper.JsonSerialize(xSplititTestMode.Value).Trim('\"') : null))
                      .Header(_header => _header.Setup("X-Splitit-TouchPoint", xSplititTouchPoint))))
              .ResponseHandler(_responseHandler => _responseHandler
                  .ErrorCase("400", CreateErrorCase("", (_reason, _context) => new PlanErrorResponseException(_reason, _context)))
                  .ErrorCase("401", CreateErrorCase("", (_reason, _context) => new FailedResponseException(_reason, _context)))
                  .ErrorCase("403", CreateErrorCase("", (_reason, _context) => new FailedResponseException(_reason, _context)))
                  .ErrorCase("404", CreateErrorCase("", (_reason, _context) => new FailedResponseException(_reason, _context)))
                  .ErrorCase("500", CreateErrorCase("", (_reason, _context) => new FailedResponseException(_reason, _context))))
              .ExecuteAsync(cancellationToken).ConfigureAwait(false);

        /// <summary>
        /// InstallmentPlan_VerifyAuthorization EndPoint.
        /// </summary>
        /// <param name="installmentPlanNumber">Required parameter: .</param>
        /// <param name="xSplititTouchPoint">Optional parameter: TouchPoint.</param>
        /// <returns>Returns the Models.VerifyAuthorizationResponse response from the API call.</returns>
        public Models.VerifyAuthorizationResponse InstallmentPlanVerifyAuthorization(
                string installmentPlanNumber,
                string xSplititTouchPoint = null)
            => CoreHelper.RunTask(InstallmentPlanVerifyAuthorizationAsync(installmentPlanNumber, xSplititTouchPoint));

        /// <summary>
        /// InstallmentPlan_VerifyAuthorization EndPoint.
        /// </summary>
        /// <param name="installmentPlanNumber">Required parameter: .</param>
        /// <param name="xSplititTouchPoint">Optional parameter: TouchPoint.</param>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the Models.VerifyAuthorizationResponse response from the API call.</returns>
        public async Task<Models.VerifyAuthorizationResponse> InstallmentPlanVerifyAuthorizationAsync(
                string installmentPlanNumber,
                string xSplititTouchPoint = null,
                CancellationToken cancellationToken = default)
            => await CreateApiCall<Models.VerifyAuthorizationResponse>()
              .RequestBuilder(_requestBuilder => _requestBuilder
                  .Setup(HttpMethod.Get, "/api/installmentplans/{installmentPlanNumber}/verifyauthorization")
                  .WithOrAuth(_orAuth => _orAuth
                      .Add("OAuth2-sandbox")
                      .Add("OAuth2-production")
                  )
                  .Parameters(_parameters => _parameters
                      .Template(_template => _template.Setup("installmentPlanNumber", installmentPlanNumber))
                      .Header(_header => _header.Setup("X-Splitit-TouchPoint", xSplititTouchPoint))))
              .ResponseHandler(_responseHandler => _responseHandler
                  .ErrorCase("401", CreateErrorCase("", (_reason, _context) => new FailedResponseException(_reason, _context)))
                  .ErrorCase("403", CreateErrorCase("", (_reason, _context) => new FailedResponseException(_reason, _context)))
                  .ErrorCase("404", CreateErrorCase("", (_reason, _context) => new FailedResponseException(_reason, _context)))
                  .ErrorCase("500", CreateErrorCase("", (_reason, _context) => new FailedResponseException(_reason, _context))))
              .ExecuteAsync(cancellationToken).ConfigureAwait(false);

        /// <summary>
        /// InstallmentPlan_UpdateOrder EndPoint.
        /// </summary>
        /// <param name="installmentPlanNumber">Required parameter: .</param>
        /// <param name="xSplititIdempotencyKey">Required parameter: .</param>
        /// <param name="body">Required parameter: .</param>
        /// <param name="xSplititTouchPoint">Optional parameter: TouchPoint.</param>
        /// <returns>Returns the Models.InstallmentPlanUpdateResponse response from the API call.</returns>
        public Models.InstallmentPlanUpdateResponse InstallmentPlanUpdateOrder(
                string installmentPlanNumber,
                string xSplititIdempotencyKey,
                Models.InstallmentPlanUpdateRequest body,
                string xSplititTouchPoint = null)
            => CoreHelper.RunTask(InstallmentPlanUpdateOrderAsync(installmentPlanNumber, xSplititIdempotencyKey, body, xSplititTouchPoint));

        /// <summary>
        /// InstallmentPlan_UpdateOrder EndPoint.
        /// </summary>
        /// <param name="installmentPlanNumber">Required parameter: .</param>
        /// <param name="xSplititIdempotencyKey">Required parameter: .</param>
        /// <param name="body">Required parameter: .</param>
        /// <param name="xSplititTouchPoint">Optional parameter: TouchPoint.</param>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the Models.InstallmentPlanUpdateResponse response from the API call.</returns>
        public async Task<Models.InstallmentPlanUpdateResponse> InstallmentPlanUpdateOrderAsync(
                string installmentPlanNumber,
                string xSplititIdempotencyKey,
                Models.InstallmentPlanUpdateRequest body,
                string xSplititTouchPoint = null,
                CancellationToken cancellationToken = default)
            => await CreateApiCall<Models.InstallmentPlanUpdateResponse>()
              .RequestBuilder(_requestBuilder => _requestBuilder
                  .Setup(HttpMethod.Put, "/api/installmentplans/{installmentPlanNumber}/updateorder")
                  .WithOrAuth(_orAuth => _orAuth
                      .Add("OAuth2-sandbox")
                      .Add("OAuth2-production")
                  )
                  .Parameters(_parameters => _parameters
                      .Body(_bodyParameter => _bodyParameter.Setup(body))
                      .Template(_template => _template.Setup("installmentPlanNumber", installmentPlanNumber))
                      .Header(_header => _header.Setup("X-Splitit-IdempotencyKey", xSplititIdempotencyKey))
                      .Header(_header => _header.Setup("Content-Type", "application/json-patch+json"))
                      .Header(_header => _header.Setup("X-Splitit-TouchPoint", xSplititTouchPoint))))
              .ResponseHandler(_responseHandler => _responseHandler
                  .ErrorCase("401", CreateErrorCase("", (_reason, _context) => new FailedResponseException(_reason, _context)))
                  .ErrorCase("403", CreateErrorCase("", (_reason, _context) => new FailedResponseException(_reason, _context)))
                  .ErrorCase("404", CreateErrorCase("", (_reason, _context) => new FailedResponseException(_reason, _context)))
                  .ErrorCase("500", CreateErrorCase("", (_reason, _context) => new FailedResponseException(_reason, _context))))
              .ExecuteAsync(cancellationToken).ConfigureAwait(false);

        /// <summary>
        /// InstallmentPlan_UpdateOrder2 EndPoint.
        /// </summary>
        /// <param name="xSplititIdempotencyKey">Required parameter: .</param>
        /// <param name="body">Required parameter: .</param>
        /// <param name="xSplititTouchPoint">Optional parameter: TouchPoint.</param>
        /// <returns>Returns the Models.InstallmentPlanUpdateResponse response from the API call.</returns>
        public Models.InstallmentPlanUpdateResponse InstallmentPlanUpdateOrder2(
                string xSplititIdempotencyKey,
                Models.InstallmentPlanUpdateRequestByIdentifier body,
                string xSplititTouchPoint = null)
            => CoreHelper.RunTask(InstallmentPlanUpdateOrder2Async(xSplititIdempotencyKey, body, xSplititTouchPoint));

        /// <summary>
        /// InstallmentPlan_UpdateOrder2 EndPoint.
        /// </summary>
        /// <param name="xSplititIdempotencyKey">Required parameter: .</param>
        /// <param name="body">Required parameter: .</param>
        /// <param name="xSplititTouchPoint">Optional parameter: TouchPoint.</param>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the Models.InstallmentPlanUpdateResponse response from the API call.</returns>
        public async Task<Models.InstallmentPlanUpdateResponse> InstallmentPlanUpdateOrder2Async(
                string xSplititIdempotencyKey,
                Models.InstallmentPlanUpdateRequestByIdentifier body,
                string xSplititTouchPoint = null,
                CancellationToken cancellationToken = default)
            => await CreateApiCall<Models.InstallmentPlanUpdateResponse>()
              .RequestBuilder(_requestBuilder => _requestBuilder
                  .Setup(HttpMethod.Put, "/api/installmentplans/updateorder")
                  .WithOrAuth(_orAuth => _orAuth
                      .Add("OAuth2-sandbox")
                      .Add("OAuth2-production")
                  )
                  .Parameters(_parameters => _parameters
                      .Body(_bodyParameter => _bodyParameter.Setup(body))
                      .Header(_header => _header.Setup("X-Splitit-IdempotencyKey", xSplititIdempotencyKey))
                      .Header(_header => _header.Setup("Content-Type", "application/json-patch+json"))
                      .Header(_header => _header.Setup("X-Splitit-TouchPoint", xSplititTouchPoint))))
              .ResponseHandler(_responseHandler => _responseHandler
                  .ErrorCase("401", CreateErrorCase("", (_reason, _context) => new FailedResponseException(_reason, _context)))
                  .ErrorCase("403", CreateErrorCase("", (_reason, _context) => new FailedResponseException(_reason, _context)))
                  .ErrorCase("404", CreateErrorCase("", (_reason, _context) => new FailedResponseException(_reason, _context)))
                  .ErrorCase("500", CreateErrorCase("", (_reason, _context) => new FailedResponseException(_reason, _context))))
              .ExecuteAsync(cancellationToken).ConfigureAwait(false);

        /// <summary>
        /// InstallmentPlan_Refund EndPoint.
        /// </summary>
        /// <param name="installmentPlanNumber">Required parameter: .</param>
        /// <param name="xSplititIdempotencyKey">Required parameter: .</param>
        /// <param name="body">Required parameter: .</param>
        /// <param name="xSplititTouchPoint">Optional parameter: TouchPoint.</param>
        /// <returns>Returns the Models.InstallmentPlanRefundResponse response from the API call.</returns>
        public Models.InstallmentPlanRefundResponse InstallmentPlanRefund(
                string installmentPlanNumber,
                string xSplititIdempotencyKey,
                Models.InstallmentPlanRefundRequest body,
                string xSplititTouchPoint = null)
            => CoreHelper.RunTask(InstallmentPlanRefundAsync(installmentPlanNumber, xSplititIdempotencyKey, body, xSplititTouchPoint));

        /// <summary>
        /// InstallmentPlan_Refund EndPoint.
        /// </summary>
        /// <param name="installmentPlanNumber">Required parameter: .</param>
        /// <param name="xSplititIdempotencyKey">Required parameter: .</param>
        /// <param name="body">Required parameter: .</param>
        /// <param name="xSplititTouchPoint">Optional parameter: TouchPoint.</param>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the Models.InstallmentPlanRefundResponse response from the API call.</returns>
        public async Task<Models.InstallmentPlanRefundResponse> InstallmentPlanRefundAsync(
                string installmentPlanNumber,
                string xSplititIdempotencyKey,
                Models.InstallmentPlanRefundRequest body,
                string xSplititTouchPoint = null,
                CancellationToken cancellationToken = default)
            => await CreateApiCall<Models.InstallmentPlanRefundResponse>()
              .RequestBuilder(_requestBuilder => _requestBuilder
                  .Setup(HttpMethod.Post, "/api/installmentplans/{installmentPlanNumber}/refund")
                  .WithOrAuth(_orAuth => _orAuth
                      .Add("OAuth2-sandbox")
                      .Add("OAuth2-production")
                  )
                  .Parameters(_parameters => _parameters
                      .Body(_bodyParameter => _bodyParameter.Setup(body))
                      .Template(_template => _template.Setup("installmentPlanNumber", installmentPlanNumber))
                      .Header(_header => _header.Setup("X-Splitit-IdempotencyKey", xSplititIdempotencyKey))
                      .Header(_header => _header.Setup("Content-Type", "application/json-patch+json"))
                      .Header(_header => _header.Setup("X-Splitit-TouchPoint", xSplititTouchPoint))))
              .ResponseHandler(_responseHandler => _responseHandler
                  .ErrorCase("401", CreateErrorCase("", (_reason, _context) => new FailedResponseException(_reason, _context)))
                  .ErrorCase("403", CreateErrorCase("", (_reason, _context) => new FailedResponseException(_reason, _context)))
                  .ErrorCase("404", CreateErrorCase("", (_reason, _context) => new FailedResponseException(_reason, _context)))
                  .ErrorCase("500", CreateErrorCase("", (_reason, _context) => new FailedResponseException(_reason, _context))))
              .ExecuteAsync(cancellationToken).ConfigureAwait(false);

        /// <summary>
        /// InstallmentPlan_CheckEligibility EndPoint.
        /// </summary>
        /// <param name="xSplititIdempotencyKey">Required parameter: .</param>
        /// <param name="body">Required parameter: .</param>
        /// <param name="xSplititTouchPoint">Optional parameter: TouchPoint.</param>
        /// <returns>Returns the Models.InstallmentsEligibilityResponse response from the API call.</returns>
        public Models.InstallmentsEligibilityResponse InstallmentPlanCheckEligibility(
                string xSplititIdempotencyKey,
                Models.CheckInstallmentsEligibilityRequest body,
                string xSplititTouchPoint = null)
            => CoreHelper.RunTask(InstallmentPlanCheckEligibilityAsync(xSplititIdempotencyKey, body, xSplititTouchPoint));

        /// <summary>
        /// InstallmentPlan_CheckEligibility EndPoint.
        /// </summary>
        /// <param name="xSplititIdempotencyKey">Required parameter: .</param>
        /// <param name="body">Required parameter: .</param>
        /// <param name="xSplititTouchPoint">Optional parameter: TouchPoint.</param>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the Models.InstallmentsEligibilityResponse response from the API call.</returns>
        public async Task<Models.InstallmentsEligibilityResponse> InstallmentPlanCheckEligibilityAsync(
                string xSplititIdempotencyKey,
                Models.CheckInstallmentsEligibilityRequest body,
                string xSplititTouchPoint = null,
                CancellationToken cancellationToken = default)
            => await CreateApiCall<Models.InstallmentsEligibilityResponse>()
              .RequestBuilder(_requestBuilder => _requestBuilder
                  .Setup(HttpMethod.Post, "/api/installmentplans/check-eligibility")
                  .WithOrAuth(_orAuth => _orAuth
                      .Add("OAuth2-sandbox")
                      .Add("OAuth2-production")
                  )
                  .Parameters(_parameters => _parameters
                      .Body(_bodyParameter => _bodyParameter.Setup(body))
                      .Header(_header => _header.Setup("X-Splitit-IdempotencyKey", xSplititIdempotencyKey))
                      .Header(_header => _header.Setup("Content-Type", "application/json-patch+json"))
                      .Header(_header => _header.Setup("X-Splitit-TouchPoint", xSplititTouchPoint))))
              .ResponseHandler(_responseHandler => _responseHandler
                  .ErrorCase("401", CreateErrorCase("", (_reason, _context) => new FailedResponseException(_reason, _context)))
                  .ErrorCase("403", CreateErrorCase("", (_reason, _context) => new FailedResponseException(_reason, _context)))
                  .ErrorCase("404", CreateErrorCase("", (_reason, _context) => new FailedResponseException(_reason, _context)))
                  .ErrorCase("500", CreateErrorCase("", (_reason, _context) => new FailedResponseException(_reason, _context))))
              .ExecuteAsync(cancellationToken).ConfigureAwait(false);

        /// <summary>
        /// InstallmentPlan_GetEligibilityTermsAndCondition EndPoint.
        /// </summary>
        /// <param name="ipn">Required parameter: .</param>
        /// <param name="xSplititTouchPoint">Optional parameter: TouchPoint.</param>
        /// <returns>Returns the Models.EligibilityTermsAndConditionResponse response from the API call.</returns>
        public Models.EligibilityTermsAndConditionResponse InstallmentPlanGetEligibilityTermsAndCondition(
                string ipn,
                string xSplititTouchPoint = null)
            => CoreHelper.RunTask(InstallmentPlanGetEligibilityTermsAndConditionAsync(ipn, xSplititTouchPoint));

        /// <summary>
        /// InstallmentPlan_GetEligibilityTermsAndCondition EndPoint.
        /// </summary>
        /// <param name="ipn">Required parameter: .</param>
        /// <param name="xSplititTouchPoint">Optional parameter: TouchPoint.</param>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the Models.EligibilityTermsAndConditionResponse response from the API call.</returns>
        public async Task<Models.EligibilityTermsAndConditionResponse> InstallmentPlanGetEligibilityTermsAndConditionAsync(
                string ipn,
                string xSplititTouchPoint = null,
                CancellationToken cancellationToken = default)
            => await CreateApiCall<Models.EligibilityTermsAndConditionResponse>()
              .RequestBuilder(_requestBuilder => _requestBuilder
                  .Setup(HttpMethod.Get, "/api/installmentplans/{ipn}/legal")
                  .WithOrAuth(_orAuth => _orAuth
                      .Add("OAuth2-sandbox")
                      .Add("OAuth2-production")
                  )
                  .Parameters(_parameters => _parameters
                      .Template(_template => _template.Setup("ipn", ipn))
                      .Header(_header => _header.Setup("X-Splitit-TouchPoint", xSplititTouchPoint))))
              .ResponseHandler(_responseHandler => _responseHandler
                  .ErrorCase("401", CreateErrorCase("", (_reason, _context) => new FailedResponseException(_reason, _context)))
                  .ErrorCase("403", CreateErrorCase("", (_reason, _context) => new FailedResponseException(_reason, _context)))
                  .ErrorCase("404", CreateErrorCase("", (_reason, _context) => new FailedResponseException(_reason, _context)))
                  .ErrorCase("500", CreateErrorCase("", (_reason, _context) => new FailedResponseException(_reason, _context))))
              .ExecuteAsync(cancellationToken).ConfigureAwait(false);
    }
}