// <copyright file="ControllerTestBase.cs" company="APIMatic">
// SplititWebApiV3.Tests
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using NUnit.Framework;
using SplititWebApiV3.Standard;
using SplititWebApiV3.Standard.Authentication;
using SplititWebApiV3.Standard.Exceptions;
using SplititWebApiV3.Standard.Http.Client;
using SplititWebApiV3.Standard.Models;

namespace SplititWebApiV3.Tests
{
    /// <summary>
    /// ControllerTestBase Class.
    /// </summary>
    [TestFixture]
    public class ControllerTestBase
    {
        /// <summary>
        /// Assert precision.
        /// </summary>
        protected const double AssertPrecision = 0.1;

        /// <summary>
        /// Gets HttpCallBackHandler.
        /// </summary>
        internal HttpCallback HttpCallBack { get; private set; } = new HttpCallback();

        /// <summary>
        /// Gets SplititWebApiV3Client Client.
        /// </summary>
        protected SplititWebApiV3Client Client { get; private set; }

        /// <summary>
        /// Set up the client.
        /// </summary>
        [OneTimeSetUp]
        public void SetUp()
        {
            SplititWebApiV3Client config = SplititWebApiV3Client.CreateFromEnvironment();
            this.Client = config.ToBuilder()
                .HttpCallback(HttpCallBack)
                .Build();


        }
    }
}