// <copyright file="InstallmentPlanControllerTest.cs" company="APIMatic">
// SplititWebApiV3.Tests
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Threading.Tasks;
using APIMatic.Core.Utilities;
using Newtonsoft.Json.Converters;
using NUnit.Framework;
using SplititWebApiV3.Standard;
using SplititWebApiV3.Standard.Controllers;
using SplititWebApiV3.Standard.Exceptions;
using SplititWebApiV3.Standard.Http.Client;
using SplititWebApiV3.Standard.Http.Response;
using SplititWebApiV3.Standard.Utilities;

namespace SplititWebApiV3.Tests
{
    /// <summary>
    /// InstallmentPlanControllerTest.
    /// </summary>
    [TestFixture]
    public class InstallmentPlanControllerTest : ControllerTestBase
    {
        /// <summary>
        /// Controller instance (for all tests).
        /// </summary>
        private InstallmentPlanController controller;

        /// <summary>
        /// Setup test class.
        /// </summary>
        [OneTimeSetUp]
        public void SetUpDerived()
        {
            this.controller = this.Client.InstallmentPlanController;
        }

        /// <summary>
        /// Testcase for testing endpoint InstallmentPlan_Search.
        /// </summary>
        /// <returns>A <see cref="Task"/> representing the asynchronous unit test.</returns>
        [Test]
        public async Task TestTestInstallmentPlanSearch2()
        {
            // Parameters for the API call
            string installmentPlanNumber = null;
            string refOrderNumber = null;
            object extendedParams = null;
            string xSplititTouchPoint = null;

            // Perform API call
            Standard.Models.InstallmentPlanSearchResponse result = null;
            try
            {
                result = await this.controller.InstallmentPlanSearchAsync(installmentPlanNumber, refOrderNumber, extendedParams, xSplititTouchPoint);
            }
            catch (ApiException)
            {
            }

            // Test response code
            Assert.AreEqual(200, HttpCallBack.Response.StatusCode, "Status should be 200");

            // Test headers
            Dictionary<string, string> headers = new Dictionary<string, string>();
            headers.Add("Content-Type", "text/json");

            Assert.IsTrue(
                    TestHelper.AreHeadersProperSubsetOf (
                    headers,
                    HttpCallBack.Response.Headers),
                    "Headers should match");
        }

        /// <summary>
        /// Testcase for testing endpoint InstallmentPlan_Search.
        /// </summary>
        /// <returns>A <see cref="Task"/> representing the asynchronous unit test.</returns>
        [Test]
        public async Task TestTestInstallmentPlanSearch()
        {
            // Parameters for the API call
            string installmentPlanNumber = null;
            string refOrderNumber = null;
            object extendedParams = null;
            string xSplititTouchPoint = null;

            // Perform API call
            Standard.Models.InstallmentPlanSearchResponse result = null;
            try
            {
                result = await this.controller.InstallmentPlanSearchAsync(installmentPlanNumber, refOrderNumber, extendedParams, xSplititTouchPoint);
            }
            catch (ApiException)
            {
            }

            // Test response code
            Assert.AreEqual(200, HttpCallBack.Response.StatusCode, "Status should be 200");

            // Test headers
            Dictionary<string, string> headers = new Dictionary<string, string>();
            headers.Add("Content-Type", "text/plain");

            Assert.IsTrue(
                    TestHelper.AreHeadersProperSubsetOf (
                    headers,
                    HttpCallBack.Response.Headers),
                    "Headers should match");
        }

        /// <summary>
        /// Testcase for testing endpoint InstallmentPlan_Search.
        /// </summary>
        /// <returns>A <see cref="Task"/> representing the asynchronous unit test.</returns>
        [Test]
        public async Task TestTestInstallmentPlanSearch1()
        {
            // Parameters for the API call
            string installmentPlanNumber = null;
            string refOrderNumber = null;
            object extendedParams = null;
            string xSplititTouchPoint = null;

            // Perform API call
            Standard.Models.InstallmentPlanSearchResponse result = null;
            try
            {
                result = await this.controller.InstallmentPlanSearchAsync(installmentPlanNumber, refOrderNumber, extendedParams, xSplititTouchPoint);
            }
            catch (ApiException)
            {
            }

            // Test response code
            Assert.AreEqual(200, HttpCallBack.Response.StatusCode, "Status should be 200");

            // Test headers
            Dictionary<string, string> headers = new Dictionary<string, string>();
            headers.Add("Content-Type", "application/json");

            Assert.IsTrue(
                    TestHelper.AreHeadersProperSubsetOf (
                    headers,
                    HttpCallBack.Response.Headers),
                    "Headers should match");
        }
    }
}