// <copyright file="IConfiguration.cs" company="APIMatic">
// SplititWebApiV3.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using System;
using System.Net;
using SplititWebApiV3.Standard.Authentication;
using SplititWebApiV3.Standard.Models;

namespace SplititWebApiV3.Standard
{
    /// <summary>
    /// IConfiguration.
    /// </summary>
    public interface IConfiguration
    {
        /// <summary>
        /// Gets Current API environment.
        /// </summary>
        Environment Environment { get; }

        /// <summary>
        /// Gets the credentials to use with OAuth2Sandbox.
        /// </summary>
        IOAuth2SandboxCredentials OAuth2SandboxCredentials { get; }

        /// <summary>
        /// Gets the credentials model to use with OAuth2Sandbox.
        /// </summary>
        OAuth2SandboxModel OAuth2SandboxModel { get; }

        /// <summary>
        /// Gets the credentials to use with OAuth2Production.
        /// </summary>
        IOAuth2ProductionCredentials OAuth2ProductionCredentials { get; }

        /// <summary>
        /// Gets the credentials model to use with OAuth2Production.
        /// </summary>
        OAuth2ProductionModel OAuth2ProductionModel { get; }

        /// <summary>
        /// Gets the URL for a particular alias in the current environment and appends it with template parameters.
        /// </summary>
        /// <param name="alias">Default value:DEFAULT.</param>
        /// <returns>Returns the baseurl.</returns>
        string GetBaseUri(Server alias = Server.Default);
    }
}