// <copyright file="Server.cs" company="APIMatic">
// SplititWebApiV3.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>

namespace SplititWebApiV3.Standard
{
    /// <summary>
    /// Available servers.
    /// </summary>
    public enum Server
    {
        /// <summary>
        /// Default.
        /// </summary>
        Default,

        /// <summary>
        /// AccessTokenServer.
        /// </summary>
        AccessTokenServer,

        /// <summary>
        /// AccessTokenServer1.
        /// </summary>
        AccessTokenServer1,
    }
}
