// <copyright file="SplititWebApiV3Client.cs" company="APIMatic">
// SplititWebApiV3.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using System;
using System.Collections.Generic;
using System.Linq;
using APIMatic.Core;
using APIMatic.Core.Authentication;
using SplititWebApiV3.Standard.Authentication;
using SplititWebApiV3.Standard.Controllers;
using SplititWebApiV3.Standard.Http.Client;
using SplititWebApiV3.Standard.Utilities;

namespace SplititWebApiV3.Standard
{
    /// <summary>
    /// The gateway for the SDK. This class acts as a factory for Controller and
    /// holds the configuration of the SDK.
    /// </summary>
    public sealed class SplititWebApiV3Client : IConfiguration
    {
        // A map of environments and their corresponding servers/baseurls
        private static readonly Dictionary<Environment, Dictionary<Enum, string>> EnvironmentsMap =
            new Dictionary<Environment, Dictionary<Enum, string>>
        {
            {
                Environment.Production, new Dictionary<Enum, string>
                {
                    { Server.Default, "https://web-api-v3.sandbox.splitit.com/" },
                    { Server.AccessTokenServer, "https://id.sandbox.splitit.com/connect" },
                    { Server.AccessTokenServer1, "https://id.splitit.com/connect" },
                }
            },
            {
                Environment.Environment2, new Dictionary<Enum, string>
                {
                    { Server.Default, "https://web-api-v3.splitit.com/" },
                    { Server.AccessTokenServer, "https://id.sandbox.splitit.com/connect" },
                    { Server.AccessTokenServer1, "https://id.splitit.com/connect" },
                }
            },
        };

        private readonly GlobalConfiguration globalConfiguration;
        private const string userAgent = "APIMATIC 3.0";
        private readonly HttpCallback httpCallback;
        private readonly Lazy<InstallmentPlanController> installmentPlan;
        private readonly Lazy<OAuthAuthorizationController> oAuthAuthorization;

        private SplititWebApiV3Client(
            Environment environment,
            OAuth2SandboxModel oAuth2SandboxModel,
            OAuth2ProductionModel oAuth2ProductionModel,
            HttpCallback httpCallback,
            IHttpClientConfiguration httpClientConfiguration)
        {
            this.Environment = environment;
            this.httpCallback = httpCallback;
            this.HttpClientConfiguration = httpClientConfiguration;
            OAuth2SandboxModel = oAuth2SandboxModel;
            var oAuth2SandboxManager = new OAuth2SandboxManager(oAuth2SandboxModel,
                () => OAuthAuthorizationController);
            OAuth2ProductionModel = oAuth2ProductionModel;
            var oAuth2ProductionManager = new OAuth2ProductionManager(oAuth2ProductionModel,
                () => OAuthAuthorizationController);
            globalConfiguration = new GlobalConfiguration.Builder()
                .AuthManagers(new Dictionary<string, AuthManager> {
                    {"OAuth2-sandbox", oAuth2SandboxManager},
                    {"OAuth2-production", oAuth2ProductionManager},
                })
                .ApiCallback(httpCallback)
                .HttpConfiguration(httpClientConfiguration)
                .ServerUrls(EnvironmentsMap[environment], Server.Default)
                .UserAgent(userAgent)
                .Build();

            OAuth2SandboxCredentials = oAuth2SandboxManager;
            OAuth2ProductionCredentials = oAuth2ProductionManager;

            this.installmentPlan = new Lazy<InstallmentPlanController>(
                () => new InstallmentPlanController(globalConfiguration));
            this.oAuthAuthorization = new Lazy<OAuthAuthorizationController>(
                () => new OAuthAuthorizationController(globalConfiguration));
        }

        /// <summary>
        /// Gets InstallmentPlanController controller.
        /// </summary>
        public InstallmentPlanController InstallmentPlanController => this.installmentPlan.Value;

        /// <summary>
        /// Gets OAuthAuthorizationController controller.
        /// </summary>
        public OAuthAuthorizationController OAuthAuthorizationController => this.oAuthAuthorization.Value;

        /// <summary>
        /// Gets the configuration of the Http Client associated with this client.
        /// </summary>
        public IHttpClientConfiguration HttpClientConfiguration { get; }

        /// <summary>
        /// Gets Environment.
        /// Current API environment.
        /// </summary>
        public Environment Environment { get; }

        /// <summary>
        /// Gets http callback.
        /// </summary>
        public HttpCallback HttpCallback => this.httpCallback;

        /// <summary>
        /// Gets the credentials to use with OAuth2Sandbox.
        /// </summary>
        public IOAuth2SandboxCredentials OAuth2SandboxCredentials { get; private set; }

        /// <summary>
        /// Gets the credentials model to use with OAuth2Sandbox.
        /// </summary>
        public OAuth2SandboxModel OAuth2SandboxModel { get; private set; }

        /// <summary>
        /// Gets the credentials to use with OAuth2Production.
        /// </summary>
        public IOAuth2ProductionCredentials OAuth2ProductionCredentials { get; private set; }

        /// <summary>
        /// Gets the credentials model to use with OAuth2Production.
        /// </summary>
        public OAuth2ProductionModel OAuth2ProductionModel { get; private set; }

        /// <summary>
        /// Gets the URL for a particular alias in the current environment and appends
        /// it with template parameters.
        /// </summary>
        /// <param name="alias">Default value:DEFAULT.</param>
        /// <returns>Returns the baseurl.</returns>
        public string GetBaseUri(Server alias = Server.Default)
        {
            return globalConfiguration.ServerUrl(alias);
        }

        /// <summary>
        /// Creates an object of the SplititWebApiV3Client using the values provided for the builder.
        /// </summary>
        /// <returns>Builder.</returns>
        public Builder ToBuilder()
        {
            Builder builder = new Builder()
                .Environment(this.Environment)
                .HttpCallback(httpCallback)
                .HttpClientConfig(config => config.Build());

            if (OAuth2SandboxModel != null)
            {
                builder.OAuth2SandboxCredentials(OAuth2SandboxModel.ToBuilder().Build());
            }

            if (OAuth2ProductionModel != null)
            {
                builder.OAuth2ProductionCredentials(OAuth2ProductionModel.ToBuilder().Build());
            }

            return builder;
        }

        /// <inheritdoc/>
        public override string ToString()
        {
            return
                $"Environment = {this.Environment}, " +
                $"HttpClientConfiguration = {this.HttpClientConfiguration}, ";
        }

        /// <summary>
        /// Creates the client using builder.
        /// </summary>
        /// <returns> SplititWebApiV3Client.</returns>
        internal static SplititWebApiV3Client CreateFromEnvironment()
        {
            var builder = new Builder();

            string environment = System.Environment.GetEnvironmentVariable("SPLITIT_WEB_API_V_3_STANDARD_ENVIRONMENT");
            string oAuthClientId = System.Environment.GetEnvironmentVariable("SPLITIT_WEB_API_V_3_STANDARD_O_AUTH_CLIENT_ID");
            string oAuthClientSecret = System.Environment.GetEnvironmentVariable("SPLITIT_WEB_API_V_3_STANDARD_O_AUTH_CLIENT_SECRET");
            string oAuthClientId2 = System.Environment.GetEnvironmentVariable("SPLITIT_WEB_API_V_3_STANDARD_O_AUTH_CLIENT_ID_2");
            string oAuthClientSecret2 = System.Environment.GetEnvironmentVariable("SPLITIT_WEB_API_V_3_STANDARD_O_AUTH_CLIENT_SECRET_2");

            if (environment != null)
            {
                builder.Environment(ApiHelper.JsonDeserialize<Environment>($"\"{environment}\""));
            }

            if (oAuthClientId != null && oAuthClientSecret != null)
            {
                builder.OAuth2SandboxCredentials(new OAuth2SandboxModel
                .Builder(oAuthClientId, oAuthClientSecret)
                .Build());
            }

            if (oAuthClientId2 != null && oAuthClientSecret2 != null)
            {
                builder.OAuth2ProductionCredentials(new OAuth2ProductionModel
                .Builder(oAuthClientId2, oAuthClientSecret2)
                .Build());
            }

            return builder.Build();
        }

        /// <summary>
        /// Builder class.
        /// </summary>
        public class Builder
        {
            private Environment environment = SplititWebApiV3.Standard.Environment.Production;
            private OAuth2SandboxModel oAuth2SandboxModel = new OAuth2SandboxModel();
            private OAuth2ProductionModel oAuth2ProductionModel = new OAuth2ProductionModel();
            private HttpClientConfiguration.Builder httpClientConfig = new HttpClientConfiguration.Builder();
            private HttpCallback httpCallback;

            /// <summary>
            /// Sets credentials for OAuth2Sandbox.
            /// </summary>
            /// <param name="oAuth2SandboxModel">OAuth2SandboxModel.</param>
            /// <returns>Builder.</returns>
            public Builder OAuth2SandboxCredentials(OAuth2SandboxModel oAuth2SandboxModel)
            {
                if (oAuth2SandboxModel is null)
                {
                    throw new ArgumentNullException(nameof(oAuth2SandboxModel));
                }

                this.oAuth2SandboxModel = oAuth2SandboxModel;
                return this;
            }

            /// <summary>
            /// Sets credentials for OAuth2Production.
            /// </summary>
            /// <param name="oAuth2ProductionModel">OAuth2ProductionModel.</param>
            /// <returns>Builder.</returns>
            public Builder OAuth2ProductionCredentials(OAuth2ProductionModel oAuth2ProductionModel)
            {
                if (oAuth2ProductionModel is null)
                {
                    throw new ArgumentNullException(nameof(oAuth2ProductionModel));
                }

                this.oAuth2ProductionModel = oAuth2ProductionModel;
                return this;
            }

            /// <summary>
            /// Sets Environment.
            /// </summary>
            /// <param name="environment"> Environment. </param>
            /// <returns> Builder. </returns>
            public Builder Environment(Environment environment)
            {
                this.environment = environment;
                return this;
            }

            /// <summary>
            /// Sets HttpClientConfig.
            /// </summary>
            /// <param name="action"> Action. </param>
            /// <returns>Builder.</returns>
            public Builder HttpClientConfig(Action<HttpClientConfiguration.Builder> action)
            {
                if (action is null)
                {
                    throw new ArgumentNullException(nameof(action));
                }

                action(this.httpClientConfig);
                return this;
            }



            /// <summary>
            /// Sets the HttpCallback for the Builder.
            /// </summary>
            /// <param name="httpCallback"> http callback. </param>
            /// <returns>Builder.</returns>
            public Builder HttpCallback(HttpCallback httpCallback)
            {
                this.httpCallback = httpCallback;
                return this;
            }

            /// <summary>
            /// Creates an object of the SplititWebApiV3Client using the values provided for the builder.
            /// </summary>
            /// <returns>SplititWebApiV3Client.</returns>
            public SplititWebApiV3Client Build()
            {
                if (oAuth2SandboxModel.OAuthClientId == null || oAuth2SandboxModel.OAuthClientSecret == null)
                {
                    oAuth2SandboxModel = null;
                }
                if (oAuth2ProductionModel.OAuthClientId == null || oAuth2ProductionModel.OAuthClientSecret == null)
                {
                    oAuth2ProductionModel = null;
                }
                return new SplititWebApiV3Client(
                    environment,
                    oAuth2SandboxModel,
                    oAuth2ProductionModel,
                    httpCallback,
                    httpClientConfig.Build());
            }
        }
    }
}
